/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.informatica.Interfaces;

/**
 *
 * @author Temporal
 */
public class CarritoCompras extends javax.swing.JFrame {

    /**
     * Creates new form CarritoCompras
     */
    private int xMouse,yMouse;
    public CarritoCompras() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelSalida = new javax.swing.JPanel();
        btnMinimizar = new javax.swing.JLabel();
        btnSalir = new javax.swing.JLabel();
        btnMaximizar = new javax.swing.JLabel();
        jPanelHeader = new javax.swing.JPanel();
        btnCarrito = new javax.swing.JLabel();
        btnMenu = new javax.swing.JButton();
        jlabelLogo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelSalida.setBackground(new java.awt.Color(73, 49, 44));
        jPanelSalida.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanelSalidaMouseDragged(evt);
            }
        });
        jPanelSalida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelSalidaMousePressed(evt);
            }
        });
        jPanelSalida.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/minimizar.png"))); // NOI18N
        btnMinimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMinimizarMouseClicked(evt);
            }
        });
        jPanelSalida.add(btnMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 14, -1, -1));

        btnSalir.setBackground(new java.awt.Color(73, 49, 44));
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salir.png"))); // NOI18N
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSalirMouseExited(evt);
            }
        });
        jPanelSalida.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 5, -1, -1));

        btnMaximizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/maximizar.png"))); // NOI18N
        btnMaximizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMaximizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMaximizarMouseClicked(evt);
            }
        });
        jPanelSalida.add(btnMaximizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 5, -1, -1));

        getContentPane().add(jPanelSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 40));

        jPanelHeader.setBackground(new java.awt.Color(193, 39, 45));
        jPanelHeader.setPreferredSize(new java.awt.Dimension(900, 180));
        jPanelHeader.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCarrito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carrito.png"))); // NOI18N
        btnCarrito.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCarrito.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCarritoMouseClicked(evt);
            }
        });
        jPanelHeader.add(btnCarrito, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 20, -1, -1));

        btnMenu.setBackground(new java.awt.Color(255, 211, 61));
        btnMenu.setFont(new java.awt.Font("Bebas Neue", 0, 48)); // NOI18N
        btnMenu.setForeground(new java.awt.Color(26, 26, 26));
        btnMenu.setText("Menú");
        btnMenu.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(193, 39, 45), 2, true));
        btnMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMenu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });
        jPanelHeader.add(btnMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 30, 120, -1));

        jlabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/donpollo-minilogo.png"))); // NOI18N
        jPanelHeader.add(jlabelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 5, -1, -1));

        getContentPane().add(jPanelHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 35, 910, 120));

        jPanel1.setBackground(new java.awt.Color(248, 245, 240));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 910, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 910, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizarMouseClicked
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_btnMinimizarMouseClicked

    private void btnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btnSalirMouseClicked

    private void btnSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseEntered

    }//GEN-LAST:event_btnSalirMouseEntered

    private void btnSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseExited

    }//GEN-LAST:event_btnSalirMouseExited

    private void btnMaximizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMaximizarMouseClicked
        this.setExtendedState(MAXIMIZED_BOTH);
    }//GEN-LAST:event_btnMaximizarMouseClicked

    private void jPanelSalidaMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelSalidaMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_jPanelSalidaMouseDragged

    private void jPanelSalidaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelSalidaMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jPanelSalidaMousePressed

    private void btnCarritoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCarritoMouseClicked
        
    }//GEN-LAST:event_btnCarritoMouseClicked

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        MenuMain main = new MenuMain();
        main.setVisible(true);
        main.setLocationRelativeTo(null);
        setVisible(false);
    }//GEN-LAST:event_btnMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CarritoCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CarritoCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CarritoCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CarritoCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CarritoCompras().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnCarrito;
    private javax.swing.JLabel btnMaximizar;
    private javax.swing.JButton btnMenu;
    private javax.swing.JLabel btnMinimizar;
    private javax.swing.JLabel btnSalir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelHeader;
    private javax.swing.JPanel jPanelSalida;
    private javax.swing.JLabel jlabelLogo;
    // End of variables declaration//GEN-END:variables
}
