/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.informatica.Interfaces;

import com.informatica.DatosModel.ItemsEnCarrito;
import com.informatica.VentanasSecundarias.CompraFinalCupon;
import com.informatica.clases.Producto;
import java.awt.*;
import java.util.ArrayList;
import javax.swing.*;

/**
 *
 * @author Temporal
 */
public class CarritoComprasView extends javax.swing.JFrame {

    /**
     * Creates new form CarritoComprasView
     */
    private int xMouse,yMouse;
    private CargarTipografias tipoFuente;
    public CarritoComprasView() {
        setUndecorated(true);
        initComponents();
        tipoFuente = new CargarTipografias();
        
        btnFinCompra.setFont(tipoFuente.fuente(tipoFuente.BebasNeue, 0, 36));
        btnVaciar.setFont(tipoFuente.fuente(tipoFuente.BebasNeue, 0, 32));
        
        jLabelTitulo.setFont(tipoFuente.fuente(tipoFuente.Lobster,0,60));
        
        cargarProductosEnCarrito();
        
        actualizarTotal();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        jPanelSalida = new javax.swing.JPanel();
        btnMinimizar = new javax.swing.JLabel();
        btnSalir = new javax.swing.JLabel();
        btnMaximizar = new javax.swing.JLabel();
        jPanelHeader = new javax.swing.JPanel();
        jlabelLogo = new javax.swing.JLabel();
        jLabelTitulo = new javax.swing.JLabel();
        btnInicio = new javax.swing.JButton();
        scrollPaneCarrito = new javax.swing.JScrollPane();
        panelProductos = new javax.swing.JPanel();
        panelInferior = new javax.swing.JPanel();
        btnVaciar = new javax.swing.JButton();
        btnFinCompra = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblTotal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setLayout(new java.awt.BorderLayout());

        jPanelSalida.setBackground(new java.awt.Color(73, 49, 44));
        jPanelSalida.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanelSalidaMouseDragged(evt);
            }
        });
        jPanelSalida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelSalidaMousePressed(evt);
            }
        });
        jPanelSalida.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/minimizar.png"))); // NOI18N
        btnMinimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMinimizarMouseClicked(evt);
            }
        });
        jPanelSalida.add(btnMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 14, -1, -1));

        btnSalir.setBackground(new java.awt.Color(73, 49, 44));
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salir.png"))); // NOI18N
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSalirMouseExited(evt);
            }
        });
        jPanelSalida.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 5, -1, -1));

        btnMaximizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/maximizar.png"))); // NOI18N
        btnMaximizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMaximizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMaximizarMouseClicked(evt);
            }
        });
        jPanelSalida.add(btnMaximizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 5, -1, -1));

        jPanelHeader.setBackground(new java.awt.Color(193, 39, 45));
        jPanelHeader.setPreferredSize(new java.awt.Dimension(900, 180));
        jPanelHeader.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/donpollo-minilogo.png"))); // NOI18N
        jPanelHeader.add(jlabelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 5, -1, -1));

        jLabelTitulo.setFont(new java.awt.Font("Lobster", 0, 60)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(248, 245, 240));
        jLabelTitulo.setText("Carrito de Compras");
        jPanelHeader.add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        btnInicio.setBackground(new java.awt.Color(255, 211, 61));
        btnInicio.setFont(new java.awt.Font("Bebas Neue", 0, 48)); // NOI18N
        btnInicio.setForeground(new java.awt.Color(26, 26, 26));
        btnInicio.setText("menú");
        btnInicio.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(193, 39, 45), 2, true));
        btnInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInicio.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });
        jPanelHeader.add(btnInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 30, 120, -1));

        jPanelSalida.add(jPanelHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 910, 120));

        mainPanel.add(jPanelSalida, java.awt.BorderLayout.NORTH);

        scrollPaneCarrito.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        panelProductos.setBackground(new java.awt.Color(248, 245, 240));
        panelProductos.setEnabled(false);
        panelProductos.setLayout(new javax.swing.BoxLayout(panelProductos, javax.swing.BoxLayout.Y_AXIS));
        scrollPaneCarrito.setViewportView(panelProductos);

        mainPanel.add(scrollPaneCarrito, java.awt.BorderLayout.CENTER);

        panelInferior.setBackground(new java.awt.Color(193, 39, 45));

        btnVaciar.setBackground(new java.awt.Color(255, 211, 61));
        btnVaciar.setFont(new java.awt.Font("Bebas Neue", 0, 32)); // NOI18N
        btnVaciar.setForeground(new java.awt.Color(26, 26, 26));
        btnVaciar.setText("Refrescar");
        btnVaciar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(26, 26, 26)));
        btnVaciar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVaciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVaciarActionPerformed(evt);
            }
        });

        btnFinCompra.setBackground(new java.awt.Color(255, 211, 61));
        btnFinCompra.setFont(new java.awt.Font("Bebas Neue", 0, 36)); // NOI18N
        btnFinCompra.setForeground(new java.awt.Color(26, 26, 26));
        btnFinCompra.setText("Finalizar Compra");
        btnFinCompra.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(26, 26, 26)));
        btnFinCompra.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFinCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinCompraActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 211, 61));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(26, 26, 26)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelInferiorLayout = new javax.swing.GroupLayout(panelInferior);
        panelInferior.setLayout(panelInferiorLayout);
        panelInferiorLayout.setHorizontalGroup(
            panelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInferiorLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(btnVaciar, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addComponent(btnFinCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
        );
        panelInferiorLayout.setVerticalGroup(
            panelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInferiorLayout.createSequentialGroup()
                .addGroup(panelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelInferiorLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelInferiorLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(panelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnVaciar)
                            .addComponent(btnFinCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(45, 45, 45))
        );

        mainPanel.add(panelInferior, java.awt.BorderLayout.PAGE_END);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 733, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizarMouseClicked
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_btnMinimizarMouseClicked

    private void btnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btnSalirMouseClicked

    private void btnSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseEntered

    }//GEN-LAST:event_btnSalirMouseEntered

    private void btnSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseExited

    }//GEN-LAST:event_btnSalirMouseExited

    private void btnMaximizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMaximizarMouseClicked
        this.setExtendedState(MAXIMIZED_BOTH);
    }//GEN-LAST:event_btnMaximizarMouseClicked

    private void jPanelSalidaMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelSalidaMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_jPanelSalidaMouseDragged

    private void jPanelSalidaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelSalidaMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jPanelSalidaMousePressed

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        MenuMain main = new MenuMain();
        main.setVisible(true);
        main.setLocationRelativeTo(null);
        setVisible(false);

    }//GEN-LAST:event_btnInicioActionPerformed

    private void btnFinCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinCompraActionPerformed
        float totalPrecio = this.calcularTotal();
        CompraFinalCupon askCupon = new  CompraFinalCupon(totalPrecio);
        askCupon.setVisible(true);
        askCupon.setLocationRelativeTo(null);
        
    }//GEN-LAST:event_btnFinCompraActionPerformed

    private void btnVaciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVaciarActionPerformed
         actualizarCarrito(); 
    
    
    }//GEN-LAST:event_btnVaciarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CarritoComprasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CarritoComprasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CarritoComprasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CarritoComprasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CarritoComprasView().setVisible(true);
            }
        });
    }
    
    public void cargarProductosEnCarrito(){
        panelProductos.removeAll();
        
        ArrayList<Producto> productos = ItemsEnCarrito.getProductos();
        
        if(productos == null || productos.isEmpty()){
            mostrarCarritoVacio();
        }else{
            for(Producto producto: productos){
                JPanel itemPanel = crearPanelProducto(producto);
                panelProductos.add(itemPanel);
                panelProductos.add(Box.createRigidArea(new Dimension(0,12)));
            }
        }
        panelProductos.revalidate();
        panelProductos.repaint();
        
    }
        
        private void mostrarCarritoVacio() {
            JLabel lblVacio = new JLabel("Tu carrito está vacío");
            lblVacio.setFont(new Font(tipoFuente.BebasNeue,0,48));
            lblVacio.setForeground(new Color(26,26,26));
            lblVacio.setAlignmentX(Component.CENTER_ALIGNMENT);
        
            panelProductos.add(Box.createVerticalGlue());
            panelProductos.add(lblVacio);
            panelProductos.add(Box.createVerticalGlue());
    }
        
        private JPanel crearPanelProducto(Producto producto){
            JPanel panel = new JPanel();
            panel.setLayout(new BorderLayout(15,10));
            
            boolean esCombo = producto.getTipo() != null && !producto.getTipo().isBlank();
            if(esCombo){
                panel.setBorder(BorderFactory.createCompoundBorder(
                BorderFactory.createLineBorder(new Color(73,49,44)), // Borde naranja
                BorderFactory.createEmptyBorder(15, 18, 15, 18)
            ));
                panel.setBackground(new Color(255, 250, 240)); // Fondo crema
                panel.setMaximumSize(new Dimension(870, 125)); // Ajustado al ancho del panel
            }else{
                panel.setBorder(BorderFactory.createCompoundBorder(
                BorderFactory.createLineBorder(new Color(200, 200, 200), 2),
                BorderFactory.createEmptyBorder(12, 18, 12, 18)
            ));
            panel.setBackground(Color.WHITE);
            panel.setMaximumSize(new Dimension(870, 100));
            }
            
            JPanel infoPanel = new JPanel();
            infoPanel.setLayout(new BoxLayout(infoPanel, BoxLayout.Y_AXIS));
            infoPanel.setBackground(esCombo ? new Color(255, 250, 240) : Color.WHITE);
            
            if (esCombo) {
            // --- COMBO ---
            // Etiqueta "COMBO"
            JLabel lblTipoCombo = new JLabel("COMBOS O PROMOCIONES");
            lblTipoCombo.setFont(new Font("Bebas Neue",Font.BOLD,18));
            lblTipoCombo.setForeground(new Color(255, 140, 0)); // Naranja oscuro
            infoPanel.add(lblTipoCombo);
            infoPanel.add(Box.createRigidArea(new Dimension(0, 5)));
            
            // Nombre del combo - Lobster para destacar
            JLabel lblNombre = new JLabel(producto.getNombre());
            lblNombre.setFont(new Font("Lobster", Font.PLAIN, 22));
            lblNombre.setForeground(new Color(51, 51, 51));
            infoPanel.add(lblNombre);
            infoPanel.add(Box.createRigidArea(new Dimension(0, 6)));
            
            // Descripción del combo
            JLabel lblDescripcion = new JLabel("<html><body style='width: 450px'>" + producto.getDescripcion() + "</body></html>");
            lblDescripcion.setFont(new Font("Bebas Neue",Font.PLAIN,16));
            lblDescripcion.setForeground(new Color(100, 100, 100));
            infoPanel.add(lblDescripcion);
            
            // Tipo de combo
            if (producto.getTipo() != null && !producto.getTipo().isEmpty()) {
                JLabel lblTipo = new JLabel("• " + producto.getTipo());
                lblTipo.setFont(new Font("Bebas Neue",Font.PLAIN,16));
                lblTipo.setForeground(new Color(120, 120, 120));
                infoPanel.add(Box.createRigidArea(new Dimension(0, 4)));
                infoPanel.add(lblTipo);
            }
            }else{
                // --- PRODUCTO SIMPLE ---
            // Descripción (nombre del producto) - Bebas Neue para texto normal
            JLabel lblDescripcion = new JLabel(producto.getDescripcion());
            lblDescripcion.setFont(new Font("Bebas Neue", Font.BOLD, 24));
            lblDescripcion.setForeground(new Color(51, 51, 51));
            infoPanel.add(lblDescripcion);
            infoPanel.add(Box.createRigidArea(new Dimension(0, 10)));
            
            // Cantidad con estilo
            JLabel lblCantidad = new JLabel("Cantidad: 1" );
            lblCantidad.setFont(new Font("Bebas Neue", Font.PLAIN, 16));
            lblCantidad.setForeground(new Color(120, 120, 120));
            infoPanel.add(lblCantidad);
            }
            JPanel precioPanel = new JPanel();
            precioPanel.setLayout(new BoxLayout(precioPanel, BoxLayout.Y_AXIS));
            precioPanel.setBackground(esCombo ? new Color(255, 250, 240) : Color.WHITE);
            precioPanel.setAlignmentY(Component.CENTER_ALIGNMENT);
        
        // Precio principal - Lobster para destacar
            JLabel lblPrecio = new JLabel(String.format("Q %.2f", producto.getPrecio()));
            lblPrecio.setFont(new Font("Lobster", Font.BOLD, 26));
            lblPrecio.setForeground(new Color(193,39,45)); // Rojo
            precioPanel.add(lblPrecio);
        
        
        // Agregar componentes al panel principal
            panel.add(infoPanel, BorderLayout.CENTER);
            panel.add(precioPanel, BorderLayout.EAST);
        
            return panel;
        }
        
         public void actualizarCarrito() {
        cargarProductosEnCarrito();
    }
         
         public float calcularTotal() {
        float total = 0;
        ArrayList<Producto> productos = ItemsEnCarrito.getProductos();
        
        if (productos != null) {
            for (Producto p : productos) {
                // Si es combo, solo sumar el precio
                boolean esCombo = p.getTipo() != null && !p.getTipo().isEmpty();
                if (esCombo) {
                    total += p.getPrecio();
                } else {
                    // Si es producto simple, multiplicar por cantidad
                    total += p.getPrecio() *1;
                }
            }
        }
        
        return total;
    }
         
         public void actualizarTotal() {
    float total = calcularTotal();
    
    lblTotal.setText(String.format("Q %.2f", total));
    lblTotal.setFont(new Font("Bebas Neue", Font.PLAIN, 28));
    lblTotal.setForeground(new Color(26,26,26));
    
}
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFinCompra;
    private javax.swing.JButton btnInicio;
    private javax.swing.JLabel btnMaximizar;
    private javax.swing.JLabel btnMinimizar;
    private javax.swing.JLabel btnSalir;
    private javax.swing.JButton btnVaciar;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelHeader;
    private javax.swing.JPanel jPanelSalida;
    private javax.swing.JLabel jlabelLogo;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel panelInferior;
    private javax.swing.JPanel panelProductos;
    private javax.swing.JScrollPane scrollPaneCarrito;
    // End of variables declaration//GEN-END:variables
}
