/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.informatica.Interfaces;

import com.informatica.DatosModel.CuponesDatos;
import com.informatica.DatosModel.DatosCarrito;
import com.informatica.DatosModel.ItemsEnCarrito;
import com.informatica.DatosModel.SesionUsuario;
import com.informatica.VentanasSecundarias.DireccionView;
import com.informatica.clases.Cupones;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.INFORMATION_MESSAGE;

/**
 *
 * @author Temporal
 */
public final class CuponAddView extends javax.swing.JFrame {

    /**
     * Creates new form CuponAddView
     */
    private int xMouse,yMouse;
    private CargarTipografias tipoFuente;
    private CuponesDatos cd;
    public CuponAddView() {
        setUndecorated(false);
        initComponents();
        
        tipoFuente = new CargarTipografias();
        jLabel1.setFont(tipoFuente.fuente(tipoFuente.BebasNeue,0,48));
        btnUsarCupon.setFont(tipoFuente.fuente(tipoFuente.BebasNeue,0,48));
        jLabelNuevoTotal.setVisible(false);
    }

    


    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelSalida = new javax.swing.JPanel();
        btnMinimizar = new javax.swing.JLabel();
        btnSalir = new javax.swing.JLabel();
        btnMaximizar = new javax.swing.JLabel();
        jPanelHeader = new javax.swing.JPanel();
        jlabelLogo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtCodCupon = new javax.swing.JTextField();
        btnUsarCupon = new javax.swing.JButton();
        btnSiguiente = new javax.swing.JButton();
        jLabelNuevoTotal = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelSalida.setBackground(new java.awt.Color(73, 49, 44));
        jPanelSalida.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanelSalidaMouseDragged(evt);
            }
        });
        jPanelSalida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelSalidaMousePressed(evt);
            }
        });
        jPanelSalida.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/minimizar.png"))); // NOI18N
        btnMinimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMinimizarMouseClicked(evt);
            }
        });
        jPanelSalida.add(btnMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 14, -1, -1));

        btnSalir.setBackground(new java.awt.Color(73, 49, 44));
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salir.png"))); // NOI18N
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSalirMouseExited(evt);
            }
        });
        jPanelSalida.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 5, -1, -1));

        btnMaximizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/maximizar.png"))); // NOI18N
        btnMaximizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMaximizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMaximizarMouseClicked(evt);
            }
        });
        jPanelSalida.add(btnMaximizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 5, -1, -1));

        getContentPane().add(jPanelSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 40));

        jPanelHeader.setBackground(new java.awt.Color(193, 39, 45));
        jPanelHeader.setPreferredSize(new java.awt.Dimension(900, 180));
        jPanelHeader.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/donpollo-minilogo.png"))); // NOI18N
        jPanelHeader.add(jlabelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 4, -1, -1));

        getContentPane().add(jPanelHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 35, 910, 120));

        jPanel1.setBackground(new java.awt.Color(248, 245, 240));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Bebas Neue", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(26, 26, 26));
        jLabel1.setText("Ingresa el codigo del cúpon:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        txtCodCupon.setBackground(new java.awt.Color(248, 245, 240));
        txtCodCupon.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        txtCodCupon.setForeground(new java.awt.Color(26, 26, 26));
        txtCodCupon.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(26, 26, 26), 2, true));
        jPanel1.add(txtCodCupon, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 40, 366, 59));

        btnUsarCupon.setBackground(new java.awt.Color(255, 211, 61));
        btnUsarCupon.setFont(new java.awt.Font("Bebas Neue", 0, 48)); // NOI18N
        btnUsarCupon.setForeground(new java.awt.Color(26, 26, 26));
        btnUsarCupon.setText("Usar Cupón");
        btnUsarCupon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsarCuponActionPerformed(evt);
            }
        });
        jPanel1.add(btnUsarCupon, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, -1, -1));

        btnSiguiente.setBackground(new java.awt.Color(255, 211, 61));
        btnSiguiente.setFont(new java.awt.Font("Bebas Neue", 0, 48)); // NOI18N
        btnSiguiente.setForeground(new java.awt.Color(26, 26, 26));
        btnSiguiente.setText("Siguiente");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });
        jPanel1.add(btnSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 190, 210, 70));

        jLabelNuevoTotal.setFont(new java.awt.Font("Bebas Neue", 0, 48)); // NOI18N
        jLabelNuevoTotal.setForeground(new java.awt.Color(26, 26, 26));
        jLabelNuevoTotal.setText("q.9999.00");
        jPanel1.add(jLabelNuevoTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 110, -1, -1));

        jLabel3.setFont(new java.awt.Font("Bebas Neue", 0, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(26, 26, 26));
        jLabel3.setText("Nuevo Total:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 910, 310));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizarMouseClicked
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_btnMinimizarMouseClicked

    private void btnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btnSalirMouseClicked

    private void btnSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseEntered

    }//GEN-LAST:event_btnSalirMouseEntered

    private void btnSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseExited

    }//GEN-LAST:event_btnSalirMouseExited

    private void btnMaximizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMaximizarMouseClicked
        this.setExtendedState(MAXIMIZED_BOTH);
    }//GEN-LAST:event_btnMaximizarMouseClicked

    private void jPanelSalidaMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelSalidaMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_jPanelSalidaMouseDragged

    private void jPanelSalidaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelSalidaMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jPanelSalidaMousePressed

    private void btnUsarCuponActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsarCuponActionPerformed
        cd = new CuponesDatos();
        DatosCarrito carrito = new DatosCarrito();
        
        int id_user = SesionUsuario.getIdUsuarioActual();
        float precioSinCupon = ItemsEnCarrito.getPrecioFinal();
        float precioConCupon = 2f;
        String codeCupon = txtCodCupon.getText();
        
        Cupones cuponUsado = cd.usarCupon(id_user, codeCupon);
        if(cuponUsado != null ){
            JOptionPane.showMessageDialog(this, "Cupon Usado con exito","Usado Exitosamente",INFORMATION_MESSAGE);
            precioConCupon = cuponUsado.getDescuento() * precioSinCupon;
            jLabelNuevoTotal.setText(String.valueOf(precioConCupon));
            jLabelNuevoTotal.setVisible(true);
            carrito.finalizarCompra(id_user, precioConCupon, codeCupon);
            ItemsEnCarrito.setPrecioFinal(precioConCupon);
        }else{
            JOptionPane.showMessageDialog(this, "Algo salio mal vuelve a intentarlo","Error",0);
        }
    }//GEN-LAST:event_btnUsarCuponActionPerformed

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        CuponesDatos asigCupon = new CuponesDatos();
        int id_user = SesionUsuario.getIdUsuarioActual();
        float precioConCupon = ItemsEnCarrito.getPrecioFinal();
        
        asigCupon.asignarCupon(id_user);
        asigCupon.asignarCupon(id_user, precioConCupon);
        DireccionView dw = new DireccionView();
            dw.setVisible(true);
            dw.setLocationRelativeTo(null);
            setVisible(false);
    }//GEN-LAST:event_btnSiguienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CuponAddView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CuponAddView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CuponAddView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CuponAddView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CuponAddView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnMaximizar;
    private javax.swing.JLabel btnMinimizar;
    private javax.swing.JLabel btnSalir;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JButton btnUsarCupon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelNuevoTotal;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelHeader;
    private javax.swing.JPanel jPanelSalida;
    private javax.swing.JLabel jlabelLogo;
    private javax.swing.JTextField txtCodCupon;
    // End of variables declaration//GEN-END:variables
}
