/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.informatica.Interfaces;



/**
 *
 * @author Temporal
 */
public class IndividualesView1 extends javax.swing.JFrame {

    /**
     * Creates new form IndividualesView
     */
    CargarTipografias tipoFuente;
    int xMouse,yMouse;
    public IndividualesView1() {
        setUndecorated(true);
        initComponents();
        tipoFuente = new CargarTipografias();
        btnMenu.setFont(tipoFuente.fuente(tipoFuente.BebasNeue,0, 48));
        lblTitulo.setFont(tipoFuente.fuente(tipoFuente.BebasNeue,0,85));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelSalida = new javax.swing.JPanel();
        btnMinimizar = new javax.swing.JLabel();
        btnSalir = new javax.swing.JLabel();
        btnMaximizar = new javax.swing.JLabel();
        jPanelHeader = new javax.swing.JPanel();
        btnCarrito = new javax.swing.JLabel();
        btnMenu = new javax.swing.JButton();
        jlabelLogo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        background = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jPanel22 = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jPanel24 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jPanel23 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jPanel25 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jPanel26 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelSalida.setBackground(new java.awt.Color(73, 49, 44));
        jPanelSalida.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanelSalidaMouseDragged(evt);
            }
        });
        jPanelSalida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelSalidaMousePressed(evt);
            }
        });
        jPanelSalida.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/minimizar.png"))); // NOI18N
        btnMinimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMinimizarMouseClicked(evt);
            }
        });
        jPanelSalida.add(btnMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 14, -1, -1));

        btnSalir.setBackground(new java.awt.Color(73, 49, 44));
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salir.png"))); // NOI18N
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSalirMouseExited(evt);
            }
        });
        jPanelSalida.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 5, -1, -1));

        btnMaximizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/maximizar.png"))); // NOI18N
        btnMaximizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMaximizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMaximizarMouseClicked(evt);
            }
        });
        jPanelSalida.add(btnMaximizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 5, -1, -1));

        getContentPane().add(jPanelSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 40));

        jPanelHeader.setBackground(new java.awt.Color(193, 39, 45));
        jPanelHeader.setPreferredSize(new java.awt.Dimension(900, 180));
        jPanelHeader.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCarrito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carrito.png"))); // NOI18N
        btnCarrito.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelHeader.add(btnCarrito, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 20, -1, -1));

        btnMenu.setBackground(new java.awt.Color(255, 211, 61));
        btnMenu.setFont(new java.awt.Font("Bebas Neue", 0, 48)); // NOI18N
        btnMenu.setForeground(new java.awt.Color(26, 26, 26));
        btnMenu.setText("MENú");
        btnMenu.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(193, 39, 45), 2, true));
        btnMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMenu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });
        jPanelHeader.add(btnMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 30, 120, -1));

        jlabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/donpollo-minilogo.png"))); // NOI18N
        jPanelHeader.add(jlabelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 5, -1, -1));

        getContentPane().add(jPanelHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 35, 910, 120));

        jScrollPane1.setBackground(new java.awt.Color(193, 39, 45));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 2));
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        background.setBackground(new java.awt.Color(248, 245, 240));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Bebas Neue", 0, 85)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(26, 26, 26));
        lblTitulo.setText("Individuales");
        lblTitulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTituloMouseClicked(evt);
            }
        });
        background.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, -1, -1));

        jPanel2.setBackground(new java.awt.Color(193, 39, 45));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(26, 26, 26));
        jLabel2.setFont(new java.awt.Font("Lobster", 0, 28)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(248, 245, 240));
        jLabel2.setText(" pollo");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, -1, 30));

        jLabel3.setBackground(new java.awt.Color(26, 26, 26));
        jLabel3.setFont(new java.awt.Font("Lobster", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(248, 245, 240));
        jLabel3.setText("Pechuga de");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pechuga.jpg"))); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 210, 100));

        background.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 210, 180));

        jPanel3.setBackground(new java.awt.Color(193, 39, 45));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setBackground(new java.awt.Color(26, 26, 26));
        jLabel6.setFont(new java.awt.Font("Lobster", 0, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(248, 245, 240));
        jLabel6.setText("Alita de");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, -1, 50));

        jLabel5.setBackground(new java.awt.Color(26, 26, 26));
        jLabel5.setFont(new java.awt.Font("Lobster", 0, 28)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(248, 245, 240));
        jLabel5.setText(" pollo");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, -1, 30));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ala.jpg"))); // NOI18N
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 210, 100));

        background.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, 210, 180));

        jPanel12.setBackground(new java.awt.Color(193, 39, 45));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setBackground(new java.awt.Color(26, 26, 26));
        jLabel7.setFont(new java.awt.Font("Lobster", 0, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(248, 245, 240));
        jLabel7.setText("Pierna de");
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel12.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, -1, 50));

        jLabel8.setBackground(new java.awt.Color(26, 26, 26));
        jLabel8.setFont(new java.awt.Font("Lobster", 0, 28)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(248, 245, 240));
        jLabel8.setText(" pollo");
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel12.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, -1, 30));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pierna.jpg"))); // NOI18N
        jPanel12.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 210, 100));

        background.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 110, 210, 180));

        jPanel8.setBackground(new java.awt.Color(193, 39, 45));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pollo_picante.jpg"))); // NOI18N
        jPanel8.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 210, 100));

        jLabel14.setBackground(new java.awt.Color(26, 26, 26));
        jLabel14.setFont(new java.awt.Font("Lobster", 0, 36)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(248, 245, 240));
        jLabel14.setText("Pollo frito");
        jLabel14.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel8.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, -1, 50));

        jLabel15.setBackground(new java.awt.Color(26, 26, 26));
        jLabel15.setFont(new java.awt.Font("Lobster", 0, 28)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(248, 245, 240));
        jLabel15.setText(" picante");
        jLabel15.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel8.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 90, 30));

        background.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 210, 180));

        jPanel9.setBackground(new java.awt.Color(193, 39, 45));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alitas.jpg"))); // NOI18N
        jPanel9.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 210, 100));

        jLabel17.setBackground(new java.awt.Color(26, 26, 26));
        jLabel17.setFont(new java.awt.Font("Lobster", 0, 36)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(248, 245, 240));
        jLabel17.setText("Alitas de ");
        jLabel17.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel9.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, -1, 50));

        jLabel18.setBackground(new java.awt.Color(26, 26, 26));
        jLabel18.setFont(new java.awt.Font("Lobster", 0, 28)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(248, 245, 240));
        jLabel18.setText(" pollo frito");
        jLabel18.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel9.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 120, -1));

        background.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 310, 210, 180));

        jPanel10.setBackground(new java.awt.Color(193, 39, 45));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tenders.jpg"))); // NOI18N
        jPanel10.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 210, 100));

        jLabel20.setBackground(new java.awt.Color(26, 26, 26));
        jLabel20.setFont(new java.awt.Font("Lobster", 0, 36)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(248, 245, 240));
        jLabel20.setText("Tenders de");
        jLabel20.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel10.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, -1, 50));

        jLabel21.setBackground(new java.awt.Color(26, 26, 26));
        jLabel21.setFont(new java.awt.Font("Lobster", 0, 28)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(248, 245, 240));
        jLabel21.setText(" pollo frito");
        jLabel21.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel10.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 120, 40));

        background.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 310, 210, 180));

        jPanel15.setBackground(new java.awt.Color(193, 39, 45));
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel27.setBackground(new java.awt.Color(26, 26, 26));
        jLabel27.setFont(new java.awt.Font("Lobster", 0, 36)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(248, 245, 240));
        jLabel27.setText("Coca cola lata");
        jLabel27.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel15.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 0, -1, 50));

        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cocalata.jpg"))); // NOI18N
        jLabel37.setToolTipText("");
        jPanel15.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 210, 100));

        background.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 510, 210, 180));

        jPanel13.setBackground(new java.awt.Color(193, 39, 45));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        background.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 510, -1, -1));

        jPanel14.setBackground(new java.awt.Color(193, 39, 45));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ensalada.jpg"))); // NOI18N
        jPanel14.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 210, 100));

        jLabel23.setBackground(new java.awt.Color(26, 26, 26));
        jLabel23.setFont(new java.awt.Font("Lobster", 0, 36)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(248, 245, 240));
        jLabel23.setText("Ensalada");
        jLabel23.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel14.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, -1, 50));

        background.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 510, 210, 180));

        jPanel16.setBackground(new java.awt.Color(193, 39, 45));
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        background.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 700, -1, -1));

        jPanel17.setBackground(new java.awt.Color(193, 39, 45));
        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        background.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 700, -1, -1));

        jPanel18.setBackground(new java.awt.Color(193, 39, 45));
        jPanel18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        background.add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 700, -1, -1));

        jLabel1.setForeground(new java.awt.Color(248, 245, 240));
        jLabel1.setText("jLabel1");
        background.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 1110, -1, 40));

        jPanel20.setBackground(new java.awt.Color(193, 39, 45));
        jPanel20.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel32.setBackground(new java.awt.Color(26, 26, 26));
        jLabel32.setFont(new java.awt.Font("Lobster", 0, 36)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(248, 245, 240));
        jLabel32.setText("Pan con pollo");
        jLabel32.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel20.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 50));

        jLabel40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/panconpollo.jpg"))); // NOI18N
        jPanel20.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 210, 100));

        background.add(jPanel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 710, 210, 180));

        jPanel21.setBackground(new java.awt.Color(193, 39, 45));
        jPanel21.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/papas_fritas.jpg"))); // NOI18N
        jPanel21.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 210, 100));

        jLabel25.setBackground(new java.awt.Color(26, 26, 26));
        jLabel25.setFont(new java.awt.Font("Lobster", 0, 36)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(248, 245, 240));
        jLabel25.setText("Papas fritas");
        jLabel25.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel21.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, 50));

        background.add(jPanel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 510, 210, 180));

        jPanel22.setBackground(new java.awt.Color(193, 39, 45));
        jPanel22.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel36.setBackground(new java.awt.Color(26, 26, 26));
        jLabel36.setFont(new java.awt.Font("Lobster", 0, 36)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(248, 245, 240));
        jLabel36.setText("Salchipapa");
        jLabel36.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel22.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, 50));

        jLabel43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salchipapa.jpg"))); // NOI18N
        jPanel22.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 210, 100));

        background.add(jPanel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 910, 210, 180));

        jPanel24.setBackground(new java.awt.Color(193, 39, 45));
        jPanel24.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel31.setBackground(new java.awt.Color(26, 26, 26));
        jLabel31.setFont(new java.awt.Font("Lobster", 0, 36)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(248, 245, 240));
        jLabel31.setText("Fresco de");
        jLabel31.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel24.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, -1, 50));

        jLabel33.setBackground(new java.awt.Color(26, 26, 26));
        jLabel33.setFont(new java.awt.Font("Lobster", 0, 28)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(248, 245, 240));
        jLabel33.setText("Crema");
        jLabel33.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel24.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 80, 40));

        jLabel39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frescocrema.jpg"))); // NOI18N
        jPanel24.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 210, 100));

        background.add(jPanel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 710, 210, 180));

        jPanel23.setBackground(new java.awt.Color(193, 39, 45));
        jPanel23.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel28.setBackground(new java.awt.Color(26, 26, 26));
        jLabel28.setFont(new java.awt.Font("Lobster", 0, 36)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(248, 245, 240));
        jLabel28.setText("Coca cola ");
        jLabel28.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel23.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, -1, 50));

        jLabel29.setBackground(new java.awt.Color(26, 26, 26));
        jLabel29.setFont(new java.awt.Font("Lobster", 0, 28)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(248, 245, 240));
        jLabel29.setText("yumbo");
        jLabel29.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel23.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 80, 40));

        jLabel38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cocajumbo.jpg"))); // NOI18N
        jPanel23.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 210, 100));

        background.add(jPanel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 710, 210, 180));

        jPanel25.setBackground(new java.awt.Color(193, 39, 45));
        jPanel25.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel26.setBackground(new java.awt.Color(26, 26, 26));
        jLabel26.setFont(new java.awt.Font("Lobster", 0, 36)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(248, 245, 240));
        jLabel26.setText("Burguer de ");
        jLabel26.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel25.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, 50));

        jLabel34.setBackground(new java.awt.Color(26, 26, 26));
        jLabel34.setFont(new java.awt.Font("Lobster", 0, 28)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(248, 245, 240));
        jLabel34.setText(" pollo frito");
        jLabel34.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel25.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 120, 40));

        jLabel41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/burguer.jpg"))); // NOI18N
        jPanel25.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 210, 100));

        background.add(jPanel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 910, 210, 180));

        jPanel26.setBackground(new java.awt.Color(193, 39, 45));
        jPanel26.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel30.setBackground(new java.awt.Color(26, 26, 26));
        jLabel30.setFont(new java.awt.Font("Lobster", 0, 36)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(248, 245, 240));
        jLabel30.setText("Tacos de ");
        jLabel30.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel26.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, -1, 50));

        jLabel35.setBackground(new java.awt.Color(26, 26, 26));
        jLabel35.setFont(new java.awt.Font("Lobster", 0, 28)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(248, 245, 240));
        jLabel35.setText(" pollo frito");
        jLabel35.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel26.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 120, 40));

        jLabel42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tacopollo.jpg"))); // NOI18N
        jPanel26.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 210, 100));

        background.add(jPanel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 910, 210, 180));

        jScrollPane1.setViewportView(background);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 910, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizarMouseClicked
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_btnMinimizarMouseClicked

    private void btnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btnSalirMouseClicked

    private void btnSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseEntered

    }//GEN-LAST:event_btnSalirMouseEntered

    private void btnSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseExited

    }//GEN-LAST:event_btnSalirMouseExited

    private void btnMaximizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMaximizarMouseClicked
        this.setExtendedState(MAXIMIZED_BOTH);
    }//GEN-LAST:event_btnMaximizarMouseClicked

    private void jPanelSalidaMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelSalidaMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_jPanelSalidaMouseDragged

    private void jPanelSalidaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelSalidaMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jPanelSalidaMousePressed

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        MenuMain main = new MenuMain();
        main.setVisible(true);
        main.setLocationRelativeTo(null);
        setVisible(false);

    }//GEN-LAST:event_btnMenuActionPerformed

    private void lblTituloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTituloMouseClicked
        MenuOpciones menu = new MenuOpciones();
        menu.setVisible(true);
        menu.setLocationRelativeTo(null);
        setVisible(false);
    }//GEN-LAST:event_lblTituloMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IndividualesView1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IndividualesView1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IndividualesView1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IndividualesView1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IndividualesView1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JLabel btnCarrito;
    private javax.swing.JLabel btnMaximizar;
    private javax.swing.JButton btnMenu;
    private javax.swing.JLabel btnMinimizar;
    private javax.swing.JLabel btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanelHeader;
    private javax.swing.JPanel jPanelSalida;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlabelLogo;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
