/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.informatica.Interfaces;

import com.informatica.DatosModel.DatosDelUsuario;
import com.informatica.clases.Usuarios_1;
import java.awt.Color;
import javax.swing.JOptionPane;


/**
 *
 * @author Temporal
 */
public class LoginView extends javax.swing.JFrame {

    /**
     * Creates new form LoginView
     */
    private CargarTipografias tipoFuente;
    private int xMouse,yMouse;
    public LoginView() {
        setUndecorated(true);
        initComponents();
        
        tipoFuente = new CargarTipografias();
        
        jlabelTitulo.setFont(tipoFuente.fuente(tipoFuente.BebasNeue, 0, 60));
        jlabelPregunta.setFont(tipoFuente.fuente(tipoFuente.BebasNeue, 0, 20));
        btnLogin.setFont(tipoFuente.fuente(tipoFuente.BebasNeue, 0, 40));
        
        btnIrRegistro.setFont(tipoFuente.fuente(tipoFuente.Lobster, 0, 20));
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        caraDonPollo = new javax.swing.JLabel();
        jPanelSalida = new javax.swing.JPanel();
        btnMinimizar = new javax.swing.JLabel();
        btnSalir = new javax.swing.JLabel();
        btnMaximizar = new javax.swing.JLabel();
        jPanelHeader = new javax.swing.JPanel();
        jPanelBackground = new javax.swing.JPanel();
        txtEmail = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        jlabelPregunta = new javax.swing.JLabel();
        btnIrRegistro = new javax.swing.JLabel();
        jlabelTitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        caraDonPollo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/caraReyPollo.png"))); // NOI18N
        getContentPane().add(caraDonPollo, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 50, -1, -1));

        jPanelSalida.setBackground(new java.awt.Color(73, 49, 44));
        jPanelSalida.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanelSalidaMouseDragged(evt);
            }
        });
        jPanelSalida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelSalidaMousePressed(evt);
            }
        });
        jPanelSalida.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/minimizar.png"))); // NOI18N
        btnMinimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMinimizarMouseClicked(evt);
            }
        });
        jPanelSalida.add(btnMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 14, -1, -1));

        btnSalir.setBackground(new java.awt.Color(73, 49, 44));
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salir.png"))); // NOI18N
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSalirMouseExited(evt);
            }
        });
        jPanelSalida.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 5, -1, -1));

        btnMaximizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/maximizar.png"))); // NOI18N
        btnMaximizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMaximizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMaximizarMouseClicked(evt);
            }
        });
        jPanelSalida.add(btnMaximizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 5, -1, -1));

        getContentPane().add(jPanelSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 40));

        jPanelHeader.setBackground(new java.awt.Color(193, 39, 45));
        jPanelHeader.setPreferredSize(new java.awt.Dimension(900, 180));
        jPanelHeader.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanelHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 35, 900, 120));

        jPanelBackground.setBackground(new java.awt.Color(248, 245, 240));
        jPanelBackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtEmail.setBackground(new java.awt.Color(248, 245, 240));
        txtEmail.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(102, 102, 102));
        txtEmail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtEmail.setText("Ingresa tu correo");
        txtEmail.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(26, 26, 26), 4, true));
        txtEmail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtEmailMousePressed(evt);
            }
        });
        jPanelBackground.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 539, 50));

        txtPassword.setBackground(new java.awt.Color(248, 245, 240));
        txtPassword.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(102, 102, 102));
        txtPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPassword.setText("******");
        txtPassword.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(26, 26, 26), 4, true));
        txtPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtPasswordMousePressed(evt);
            }
        });
        jPanelBackground.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, 539, 50));

        btnLogin.setBackground(new java.awt.Color(255, 211, 61));
        btnLogin.setForeground(new java.awt.Color(26, 26, 26));
        btnLogin.setText("Iniciar Sesión");
        btnLogin.setAlignmentX(0.5F);
        btnLogin.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(248, 245, 240), 2, true));
        btnLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        jPanelBackground.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 430, 250, 66));

        jlabelPregunta.setForeground(new java.awt.Color(26, 26, 26));
        jlabelPregunta.setText("¿No tienes una cuenta?");
        jPanelBackground.add(jlabelPregunta, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 520, -1, -1));

        btnIrRegistro.setBackground(new java.awt.Color(193, 39, 45));
        btnIrRegistro.setForeground(new java.awt.Color(193, 39, 45));
        btnIrRegistro.setText("Crea una");
        btnIrRegistro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIrRegistro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIrRegistroMouseClicked(evt);
            }
        });
        jPanelBackground.add(btnIrRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 518, -1, -1));

        jlabelTitulo.setBackground(new java.awt.Color(26, 26, 26));
        jlabelTitulo.setForeground(new java.awt.Color(26, 26, 26));
        jlabelTitulo.setText("Inicio de Sesión");
        jPanelBackground.add(jlabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, -1, -1));

        getContentPane().add(jPanelBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 900, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btnSalirMouseClicked

    private void btnMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizarMouseClicked
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_btnMinimizarMouseClicked

    private void btnMaximizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMaximizarMouseClicked
        this.setExtendedState(MAXIMIZED_BOTH);
    }//GEN-LAST:event_btnMaximizarMouseClicked

    private void jPanelSalidaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelSalidaMousePressed
       xMouse = evt.getX();
       yMouse = evt.getY();
    }//GEN-LAST:event_jPanelSalidaMousePressed

    private void jPanelSalidaMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelSalidaMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_jPanelSalidaMouseDragged

    private void btnSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseEntered
        btnSalir.setBackground(new Color(193,39,45));
    }//GEN-LAST:event_btnSalirMouseEntered

    private void btnSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseExited
        btnSalir.setBackground(new Color(73,49,44));
    }//GEN-LAST:event_btnSalirMouseExited

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
       String correo = txtEmail.getText().trim();
       String contra = new String(txtPassword.getPassword());
       contra.trim();
       
       Usuarios_1 user  = new Usuarios_1(correo,contra);
       DatosDelUsuario userAdmin = new  DatosDelUsuario();
       Usuarios_1 userFinal = userAdmin.iniciarSesion(user);
       if(userFinal != null){
          MenuMain menu = new MenuMain();
          menu.setVisible(true);
          menu.setLocationRelativeTo(null);
          setVisible(false);
       }else{
            JOptionPane.showMessageDialog(null, "Credenciales invalidas", "Error", 0);
       }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnIrRegistroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIrRegistroMouseClicked
        RegistroView registro = new RegistroView();
        registro.setVisible(true);
        registro.setLocationRelativeTo(null);
        setVisible(false);
    }//GEN-LAST:event_btnIrRegistroMouseClicked

    private void txtEmailMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtEmailMousePressed
        if(txtEmail.getText().equals("Ingresa tu correo")){
            txtEmail.setText("");
            txtEmail.setForeground(new Color(26,26,26));
        }
        if(String.valueOf(txtPassword.getPassword()).isEmpty()){
            txtPassword.setText("******");
            txtPassword.setForeground(new Color(102,102,102));
        }
    }//GEN-LAST:event_txtEmailMousePressed

    private void txtPasswordMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPasswordMousePressed
        if(String.valueOf(txtPassword.getPassword()).equals("******")) {
            txtPassword.setText("");
            txtPassword.setForeground(new Color(26,26,26));
        }
        if(txtEmail.getText().isEmpty()){
            txtEmail.setText("Ingresa tu correo");
            txtEmail.setForeground(new Color(102,102,102));
        }
    }//GEN-LAST:event_txtPasswordMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnIrRegistro;
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel btnMaximizar;
    private javax.swing.JLabel btnMinimizar;
    private javax.swing.JLabel btnSalir;
    private javax.swing.JLabel caraDonPollo;
    private javax.swing.JPanel jPanelBackground;
    private javax.swing.JPanel jPanelHeader;
    private javax.swing.JPanel jPanelSalida;
    private javax.swing.JLabel jlabelPregunta;
    private javax.swing.JLabel jlabelTitulo;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables
}
