/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.informatica.Interfaces;

import com.informatica.clases.Usuarios_1;
import javax.swing.JOptionPane;

/**
 *
 * @author Temporal
 */
public class MenuMain extends javax.swing.JFrame {

    /**
     * Creates new form MenuMain
     */
    int xMouse,yMouse;
    private CargarTipografias tipoFuente;
    public MenuMain() {
        setUndecorated(true);
        initComponents();
        
        tipoFuente = new CargarTipografias();
        
        btnCupon.setFont(tipoFuente.fuente(tipoFuente.BebasNeue, 0, 48));
        labelComo1.setFont(tipoFuente.fuente(tipoFuente.BebasNeue,0,60));
        labelComo2.setFont(tipoFuente.fuente(tipoFuente.BebasNeue,0,60));
        labelPlebeyo.setFont(tipoFuente.fuente(tipoFuente.BebasNeue, 0,80));
        labelAnuncio.setFont(tipoFuente.fuente(tipoFuente.BebasNeue, 0,24));
        labelDonPollo.setFont(tipoFuente.fuente(tipoFuente.BebasNeue,0,85));
        btnOrdenar.setFont(tipoFuente.fuente(tipoFuente.BebasNeue,0,48));
        
        labelCantDesc.setFont(tipoFuente.fuente(tipoFuente.Lobster,0,48));
        labelNoComas.setFont(tipoFuente.fuente(tipoFuente.Lobster,0,70));
        labelCome.setFont(tipoFuente.fuente(tipoFuente.Lobster,0,70));
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelSalida = new javax.swing.JPanel();
        btnMinimizar = new javax.swing.JLabel();
        btnSalir = new javax.swing.JLabel();
        btnMaximizar = new javax.swing.JLabel();
        jPanelHeader1 = new javax.swing.JPanel();
        btnLogin = new javax.swing.JLabel();
        btnCarrito = new javax.swing.JLabel();
        btnCupon = new javax.swing.JButton();
        jlabelLogo = new javax.swing.JLabel();
        background = new javax.swing.JPanel();
        labelImgPollo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        labelCantDesc = new javax.swing.JLabel();
        labelAnuncio = new javax.swing.JLabel();
        imgCupon = new javax.swing.JLabel();
        btnOrdenar = new javax.swing.JButton();
        labelNoComas = new javax.swing.JLabel();
        labelComo2 = new javax.swing.JLabel();
        labelPlebeyo = new javax.swing.JLabel();
        labelCome = new javax.swing.JLabel();
        labelComo1 = new javax.swing.JLabel();
        labelDonPollo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelSalida.setBackground(new java.awt.Color(73, 49, 44));
        jPanelSalida.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanelSalidaMouseDragged(evt);
            }
        });
        jPanelSalida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelSalidaMousePressed(evt);
            }
        });
        jPanelSalida.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/minimizar.png"))); // NOI18N
        btnMinimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMinimizarMouseClicked(evt);
            }
        });
        jPanelSalida.add(btnMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 14, -1, -1));

        btnSalir.setBackground(new java.awt.Color(73, 49, 44));
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salir.png"))); // NOI18N
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSalirMouseExited(evt);
            }
        });
        jPanelSalida.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 5, -1, -1));

        btnMaximizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/maximizar.png"))); // NOI18N
        btnMaximizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMaximizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMaximizarMouseClicked(evt);
            }
        });
        jPanelSalida.add(btnMaximizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 5, -1, -1));

        getContentPane().add(jPanelSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, -1));

        jPanelHeader1.setBackground(new java.awt.Color(193, 39, 45));
        jPanelHeader1.setPreferredSize(new java.awt.Dimension(900, 180));

        btnLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/perfil.png"))); // NOI18N
        btnLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLoginMouseClicked(evt);
            }
        });

        btnCarrito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carrito.png"))); // NOI18N
        btnCarrito.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnCupon.setBackground(new java.awt.Color(255, 211, 61));
        btnCupon.setFont(new java.awt.Font("Bebas Neue", 0, 48)); // NOI18N
        btnCupon.setForeground(new java.awt.Color(26, 26, 26));
        btnCupon.setText("CUPÓN");
        btnCupon.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(193, 39, 45), 2, true));
        btnCupon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCupon.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jlabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/donpollo-minilogo.png"))); // NOI18N
        jlabelLogo.setText("jLabel1");

        javax.swing.GroupLayout jPanelHeader1Layout = new javax.swing.GroupLayout(jPanelHeader1);
        jPanelHeader1.setLayout(jPanelHeader1Layout);
        jPanelHeader1Layout.setHorizontalGroup(
            jPanelHeader1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelHeader1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jlabelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 371, Short.MAX_VALUE)
                .addComponent(btnCupon, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLogin)
                .addGap(18, 18, 18)
                .addComponent(btnCarrito)
                .addGap(16, 16, 16))
        );
        jPanelHeader1Layout.setVerticalGroup(
            jPanelHeader1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHeader1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanelHeader1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCarrito)
                    .addComponent(btnLogin)
                    .addGroup(jPanelHeader1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(btnCupon)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelHeader1Layout.createSequentialGroup()
                .addComponent(jlabelLogo)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelHeader1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 36, 910, 120));

        background.setBackground(new java.awt.Color(248, 245, 240));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelImgPollo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img-pollo.png"))); // NOI18N
        background.add(labelImgPollo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 24, -1, 439));

        jSeparator1.setBackground(new java.awt.Color(73, 49, 44));
        jSeparator1.setForeground(new java.awt.Color(73, 49, 44));
        background.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 130, 224, 13));

        jSeparator2.setBackground(new java.awt.Color(73, 49, 44));
        jSeparator2.setForeground(new java.awt.Color(73, 49, 44));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        background.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 30, 10, 100));

        labelCantDesc.setFont(new java.awt.Font("Lobster", 0, 48)); // NOI18N
        labelCantDesc.setForeground(new java.awt.Color(26, 26, 26));
        labelCantDesc.setText("5%");
        background.add(labelCantDesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 30, -1, -1));

        labelAnuncio.setFont(new java.awt.Font("Bebas Neue", 0, 24)); // NOI18N
        labelAnuncio.setForeground(new java.awt.Color(26, 26, 26));
        labelAnuncio.setText("Reclama tu cupón por registrarte!!");
        background.add(labelAnuncio, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 90, -1, -1));

        imgCupon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cupon.png"))); // NOI18N
        background.add(imgCupon, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 40, -1, -1));

        btnOrdenar.setBackground(new java.awt.Color(255, 211, 61));
        btnOrdenar.setFont(new java.awt.Font("Bebas Neue", 0, 48)); // NOI18N
        btnOrdenar.setForeground(new java.awt.Color(26, 26, 26));
        btnOrdenar.setText("ordenar");
        btnOrdenar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(248, 245, 240), 2, true));
        btnOrdenar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnOrdenar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnOrdenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrdenarActionPerformed(evt);
            }
        });
        background.add(btnOrdenar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 460, 153, -1));

        labelNoComas.setFont(new java.awt.Font("Lobster", 0, 70)); // NOI18N
        labelNoComas.setForeground(new java.awt.Color(26, 26, 26));
        labelNoComas.setText("No comas");
        background.add(labelNoComas, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 120, -1, -1));

        labelComo2.setFont(new java.awt.Font("Bebas Neue", 0, 60)); // NOI18N
        labelComo2.setForeground(new java.awt.Color(26, 26, 26));
        labelComo2.setText("como");
        background.add(labelComo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 290, -1, -1));

        labelPlebeyo.setFont(new java.awt.Font("Bebas Neue", 0, 80)); // NOI18N
        labelPlebeyo.setForeground(new java.awt.Color(26, 26, 26));
        labelPlebeyo.setText("PLEBEYO");
        background.add(labelPlebeyo, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 200, -1, -1));

        labelCome.setFont(new java.awt.Font("Lobster", 0, 70)); // NOI18N
        labelCome.setForeground(new java.awt.Color(26, 26, 26));
        labelCome.setText("Come");
        background.add(labelCome, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 270, -1, -1));

        labelComo1.setFont(new java.awt.Font("Bebas Neue", 0, 60)); // NOI18N
        labelComo1.setForeground(new java.awt.Color(26, 26, 26));
        labelComo1.setText("como");
        background.add(labelComo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 140, -1, -1));

        labelDonPollo.setFont(new java.awt.Font("Bebas Neue", 0, 85)); // NOI18N
        labelDonPollo.setForeground(new java.awt.Color(26, 26, 26));
        labelDonPollo.setText("DON POLLO!!");
        background.add(labelDonPollo, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 350, -1, -1));

        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 156, 910, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizarMouseClicked
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_btnMinimizarMouseClicked

    private void btnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btnSalirMouseClicked

    private void btnSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseEntered
    }//GEN-LAST:event_btnSalirMouseEntered

    private void btnSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseExited
    }//GEN-LAST:event_btnSalirMouseExited

    private void btnMaximizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMaximizarMouseClicked
        this.setExtendedState(MAXIMIZED_BOTH);
    }//GEN-LAST:event_btnMaximizarMouseClicked

    private void jPanelSalidaMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelSalidaMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_jPanelSalidaMouseDragged

    private void jPanelSalidaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelSalidaMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jPanelSalidaMousePressed

    private void btnLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseClicked
        LoginView login = new LoginView();
        login.setVisible(true);
        login.setLocationRelativeTo(null);
        setVisible(false);
    }//GEN-LAST:event_btnLoginMouseClicked

    private void btnOrdenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdenarActionPerformed
        Usuarios_1 user = new Usuarios_1();
        if(user.isEstaLogeado() == true ){
            MenuOpciones menuO = new MenuOpciones();
            menuO.setVisible(true);
            menuO.setLocationRelativeTo(null);
            setVisible(false);
         }else{
            JOptionPane.showMessageDialog(this, 
            "Debes iniciar sesión para realizar un pedido", 
            "Iniciar Sesión Requerido", 
            JOptionPane.WARNING_MESSAGE);
            LoginView login = new LoginView();
            login.setVisible(true);
            login.setLocationRelativeTo(null);
        setVisible(false);
        }
        
    }//GEN-LAST:event_btnOrdenarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JLabel btnCarrito;
    private javax.swing.JButton btnCupon;
    private javax.swing.JLabel btnLogin;
    private javax.swing.JLabel btnMaximizar;
    private javax.swing.JLabel btnMinimizar;
    private javax.swing.JButton btnOrdenar;
    private javax.swing.JLabel btnSalir;
    private javax.swing.JLabel imgCupon;
    private javax.swing.JPanel jPanelHeader1;
    private javax.swing.JPanel jPanelSalida;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel jlabelLogo;
    private javax.swing.JLabel labelAnuncio;
    private javax.swing.JLabel labelCantDesc;
    private javax.swing.JLabel labelCome;
    private javax.swing.JLabel labelComo1;
    private javax.swing.JLabel labelComo2;
    private javax.swing.JLabel labelDonPollo;
    private javax.swing.JLabel labelImgPollo;
    private javax.swing.JLabel labelNoComas;
    private javax.swing.JLabel labelPlebeyo;
    // End of variables declaration//GEN-END:variables
}
