/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.informatica.Interfaces;

/**
 *
 * @author Temporal
 */
public class MenuOpciones extends javax.swing.JFrame {

    /**
     * Creates new form MenuOpciones
     */
    private CargarTipografias tipoFuente;
    int xMouse,yMouse;
    public MenuOpciones() {
        setUndecorated(true);
        initComponents();
        tipoFuente = new CargarTipografias();
        
        tituloh1.setFont(tipoFuente.fuente(tipoFuente.BebasNeue, 0, 85));
        btnInicio.setFont(tipoFuente.fuente(tipoFuente.BebasNeue, 0, 48));
        
        lblCombo.setFont(tipoFuente.fuente(tipoFuente.Lobster, 0, 48));
        lblPromo.setFont(tipoFuente.fuente(tipoFuente.Lobster, 0, 48));
        lblIndividual.setFont(tipoFuente.fuente(tipoFuente.Lobster, 0, 48));
        lblPostres.setFont(tipoFuente.fuente(tipoFuente.Lobster, 0, 48));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelSalida = new javax.swing.JPanel();
        btnMinimizar = new javax.swing.JLabel();
        btnSalir = new javax.swing.JLabel();
        btnMaximizar = new javax.swing.JLabel();
        jPanelHeader = new javax.swing.JPanel();
        btnCarrito = new javax.swing.JLabel();
        btnInicio = new javax.swing.JButton();
        jlabelLogo = new javax.swing.JLabel();
        background = new javax.swing.JPanel();
        tituloh1 = new javax.swing.JLabel();
        combo_bckg = new javax.swing.JPanel();
        lblCombo = new javax.swing.JLabel();
        img_combos = new javax.swing.JLabel();
        promo_bckg = new javax.swing.JPanel();
        lblPromo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        indi_bckg = new javax.swing.JPanel();
        lblIndividual = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        postres_bckg = new javax.swing.JPanel();
        lblPostres = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelSalida.setBackground(new java.awt.Color(73, 49, 44));
        jPanelSalida.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanelSalidaMouseDragged(evt);
            }
        });
        jPanelSalida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelSalidaMousePressed(evt);
            }
        });
        jPanelSalida.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/minimizar.png"))); // NOI18N
        btnMinimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMinimizarMouseClicked(evt);
            }
        });
        jPanelSalida.add(btnMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 14, -1, -1));

        btnSalir.setBackground(new java.awt.Color(73, 49, 44));
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salir.png"))); // NOI18N
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSalirMouseExited(evt);
            }
        });
        jPanelSalida.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 5, -1, -1));

        btnMaximizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/maximizar.png"))); // NOI18N
        btnMaximizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMaximizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMaximizarMouseClicked(evt);
            }
        });
        jPanelSalida.add(btnMaximizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 5, -1, -1));

        getContentPane().add(jPanelSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 40));

        jPanelHeader.setBackground(new java.awt.Color(193, 39, 45));
        jPanelHeader.setPreferredSize(new java.awt.Dimension(900, 180));
        jPanelHeader.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCarrito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carrito.png"))); // NOI18N
        btnCarrito.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelHeader.add(btnCarrito, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 20, -1, -1));

        btnInicio.setBackground(new java.awt.Color(255, 211, 61));
        btnInicio.setFont(new java.awt.Font("Bebas Neue", 0, 48)); // NOI18N
        btnInicio.setForeground(new java.awt.Color(26, 26, 26));
        btnInicio.setText("inicio");
        btnInicio.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(193, 39, 45), 2, true));
        btnInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInicio.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });
        jPanelHeader.add(btnInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 30, 120, -1));

        jlabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/donpollo-minilogo.png"))); // NOI18N
        jPanelHeader.add(jlabelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 5, -1, -1));

        getContentPane().add(jPanelHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 35, 910, 120));

        background.setBackground(new java.awt.Color(248, 245, 240));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tituloh1.setFont(new java.awt.Font("Bebas Neue", 0, 85)); // NOI18N
        tituloh1.setForeground(new java.awt.Color(26, 26, 26));
        tituloh1.setText("MENÚ");
        background.add(tituloh1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, -1, -1));

        combo_bckg.setBackground(new java.awt.Color(193, 39, 45));
        combo_bckg.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        combo_bckg.setVerifyInputWhenFocusTarget(false);
        combo_bckg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                combo_bckgMouseClicked(evt);
            }
        });

        lblCombo.setBackground(new java.awt.Color(248, 245, 240));
        lblCombo.setFont(new java.awt.Font("Lobster", 0, 48)); // NOI18N
        lblCombo.setForeground(new java.awt.Color(248, 245, 240));
        lblCombo.setText("Combos");

        img_combos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/combos-img.png"))); // NOI18N

        javax.swing.GroupLayout combo_bckgLayout = new javax.swing.GroupLayout(combo_bckg);
        combo_bckg.setLayout(combo_bckgLayout);
        combo_bckgLayout.setHorizontalGroup(
            combo_bckgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(img_combos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(combo_bckgLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(lblCombo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        combo_bckgLayout.setVerticalGroup(
            combo_bckgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(combo_bckgLayout.createSequentialGroup()
                .addComponent(lblCombo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(img_combos, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        background.add(combo_bckg, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, -1, -1));

        promo_bckg.setBackground(new java.awt.Color(193, 39, 45));
        promo_bckg.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        promo_bckg.setVerifyInputWhenFocusTarget(false);
        promo_bckg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                promo_bckgMouseClicked(evt);
            }
        });

        lblPromo.setFont(new java.awt.Font("Lobster", 0, 48)); // NOI18N
        lblPromo.setForeground(new java.awt.Color(248, 245, 240));
        lblPromo.setText("Promociones");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/promo-img.png"))); // NOI18N

        javax.swing.GroupLayout promo_bckgLayout = new javax.swing.GroupLayout(promo_bckg);
        promo_bckg.setLayout(promo_bckgLayout);
        promo_bckgLayout.setHorizontalGroup(
            promo_bckgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(promo_bckgLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(lblPromo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        promo_bckgLayout.setVerticalGroup(
            promo_bckgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(promo_bckgLayout.createSequentialGroup()
                .addComponent(lblPromo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        background.add(promo_bckg, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 100, -1, -1));

        indi_bckg.setBackground(new java.awt.Color(193, 39, 45));
        indi_bckg.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        indi_bckg.setVerifyInputWhenFocusTarget(false);
        indi_bckg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                indi_bckgMouseClicked(evt);
            }
        });

        lblIndividual.setBackground(new java.awt.Color(248, 245, 240));
        lblIndividual.setFont(new java.awt.Font("Lobster", 0, 48)); // NOI18N
        lblIndividual.setForeground(new java.awt.Color(248, 245, 240));
        lblIndividual.setText("Individuales");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/individuales-img.png"))); // NOI18N

        javax.swing.GroupLayout indi_bckgLayout = new javax.swing.GroupLayout(indi_bckg);
        indi_bckg.setLayout(indi_bckgLayout);
        indi_bckgLayout.setHorizontalGroup(
            indi_bckgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(indi_bckgLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(lblIndividual)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        indi_bckgLayout.setVerticalGroup(
            indi_bckgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(indi_bckgLayout.createSequentialGroup()
                .addComponent(lblIndividual)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        background.add(indi_bckg, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, -1, 220));

        postres_bckg.setBackground(new java.awt.Color(193, 39, 45));
        postres_bckg.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        postres_bckg.setVerifyInputWhenFocusTarget(false);
        postres_bckg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                postres_bckgMouseClicked(evt);
            }
        });

        lblPostres.setFont(new java.awt.Font("Lobster", 0, 48)); // NOI18N
        lblPostres.setForeground(new java.awt.Color(248, 245, 240));
        lblPostres.setText("Postres");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/postres-img.png"))); // NOI18N

        javax.swing.GroupLayout postres_bckgLayout = new javax.swing.GroupLayout(postres_bckg);
        postres_bckg.setLayout(postres_bckgLayout);
        postres_bckgLayout.setHorizontalGroup(
            postres_bckgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(postres_bckgLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(lblPostres)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        postres_bckgLayout.setVerticalGroup(
            postres_bckgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(postres_bckgLayout.createSequentialGroup()
                .addComponent(lblPostres)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        background.add(postres_bckg, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 330, -1, 220));

        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 910, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizarMouseClicked
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_btnMinimizarMouseClicked

    private void btnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btnSalirMouseClicked

    private void btnSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseEntered
    }//GEN-LAST:event_btnSalirMouseEntered

    private void btnSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseExited
    }//GEN-LAST:event_btnSalirMouseExited

    private void btnMaximizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMaximizarMouseClicked
        this.setExtendedState(MAXIMIZED_BOTH);
    }//GEN-LAST:event_btnMaximizarMouseClicked

    private void jPanelSalidaMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelSalidaMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_jPanelSalidaMouseDragged

    private void jPanelSalidaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelSalidaMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jPanelSalidaMousePressed

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        MenuMain main = new MenuMain();
        main.setVisible(true);
        main.setLocationRelativeTo(null);
        setVisible(false);
        
    }//GEN-LAST:event_btnInicioActionPerformed

    private void combo_bckgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_combo_bckgMouseClicked
        CombosView comboView = new CombosView();
        comboView.setVisible(true);
        comboView.setLocationRelativeTo(null);
        setVisible(false);
    }//GEN-LAST:event_combo_bckgMouseClicked

    private void promo_bckgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_promo_bckgMouseClicked
        PromosView promo = new PromosView();
        promo.setVisible(true);
        promo.setLocationRelativeTo(null);
        setVisible(false);
    }//GEN-LAST:event_promo_bckgMouseClicked

    private void indi_bckgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_indi_bckgMouseClicked
        IndividualesView1 indiMenu = new IndividualesView1();
        indiMenu.setVisible(true);
        indiMenu.setLocationRelativeTo(null);
        setVisible(false);
    }//GEN-LAST:event_indi_bckgMouseClicked

    private void postres_bckgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_postres_bckgMouseClicked
        PostresView postreMenu = new PostresView();
        postreMenu.setVisible(true);
        postreMenu.setLocationRelativeTo(null);
        setVisible(false);
    }//GEN-LAST:event_postres_bckgMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuOpciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuOpciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuOpciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuOpciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuOpciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JLabel btnCarrito;
    private javax.swing.JButton btnInicio;
    private javax.swing.JLabel btnMaximizar;
    private javax.swing.JLabel btnMinimizar;
    private javax.swing.JLabel btnSalir;
    private javax.swing.JPanel combo_bckg;
    private javax.swing.JLabel img_combos;
    private javax.swing.JPanel indi_bckg;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanelHeader;
    private javax.swing.JPanel jPanelSalida;
    private javax.swing.JLabel jlabelLogo;
    private javax.swing.JLabel lblCombo;
    private javax.swing.JLabel lblIndividual;
    private javax.swing.JLabel lblPostres;
    private javax.swing.JLabel lblPromo;
    private javax.swing.JPanel postres_bckg;
    private javax.swing.JPanel promo_bckg;
    private javax.swing.JLabel tituloh1;
    // End of variables declaration//GEN-END:variables
}
