/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.informatica.Interfaces;

import com.informatica.VentanasSecundarias.PanelDescripcionDeCompra;
import com.informatica.clases.CarritoDeCompras;
import com.informatica.clases.Producto;
import java.awt.Image;
import javax.swing.*;
/**
 *
 * @author Temporal
 */
public class PostresView1 extends javax.swing.JFrame {

    /**
     * Creates new form PostresView
     */
    int xMouse,yMouse;
    private CarritoDeCompras carrito = new CarritoDeCompras();
    private Producto producto;
    private PanelDescripcionDeCompra opcUsuario;
    private  CargarTipografias tipoFuente;
    public PostresView1() {
        setUndecorated(true);
        initComponents();
        tipoFuente = new CargarTipografias();
        btnMenu.setFont(tipoFuente.fuente(tipoFuente.BebasNeue,0, 48));
        lblTitulo.setFont(tipoFuente.fuente(tipoFuente.BebasNeue,0,85));
        
        //Asignacion de fuentes a los titulos mayores
        jh2_1.setFont(tipoFuente.fuente(tipoFuente.Lobster,0,36));
        jh2_2.setFont(tipoFuente.fuente(tipoFuente.Lobster,0,36));
        jh2_3.setFont(tipoFuente.fuente(tipoFuente.Lobster,0,36));
        jh2_4.setFont(tipoFuente.fuente(tipoFuente.Lobster,0,36));
        jh2_5.setFont(tipoFuente.fuente(tipoFuente.Lobster,0,36));
        
        //Asignacion de fuentes a los titulos menores
        
        jLabelPollo1.setFont(tipoFuente.fuente(tipoFuente.Lobster, 0,28));
        jLabelPollo2.setFont(tipoFuente.fuente(tipoFuente.Lobster, 0,28));
        jLabelPollo3.setFont(tipoFuente.fuente(tipoFuente.Lobster, 0,28));
        jLabelPollo4.setFont(tipoFuente.fuente(tipoFuente.Lobster, 0,28));
        jLabelPollo5.setFont(tipoFuente.fuente(tipoFuente.Lobster, 0,28));
        
         setImageLabel(jLabel20,"src/main/resources/PastelChoco.jpeg");
         setImageLabel(jLabel21,"src/main/resources/HeladoVainilla.jpeg");
         setImageLabel(jLabel23,"src/main/resources/Pay.jpeg");
         setImageLabel(jLabel15,"src/main/resources/HeladoSundae.jpeg");
         setImageLabel(jLabel17,"src/main/resources/FlanCaramelo.jpeg");
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelSalida = new javax.swing.JPanel();
        btnMinimizar = new javax.swing.JLabel();
        btnSalir = new javax.swing.JLabel();
        btnMaximizar = new javax.swing.JLabel();
        jPanelHeader = new javax.swing.JPanel();
        btnCarrito = new javax.swing.JLabel();
        btnMenu = new javax.swing.JButton();
        jlabelLogo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        background = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        jPanelPechuga = new javax.swing.JPanel();
        jLabelPollo1 = new javax.swing.JLabel();
        jh2_1 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPanelAlita = new javax.swing.JPanel();
        jh2_2 = new javax.swing.JLabel();
        jLabelPollo2 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jPanelPierna = new javax.swing.JPanel();
        jh2_3 = new javax.swing.JLabel();
        jLabelPollo3 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jPanelPicantePollo = new javax.swing.JPanel();
        jh2_4 = new javax.swing.JLabel();
        jLabelPollo4 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanelAlitas = new javax.swing.JPanel();
        jh2_5 = new javax.swing.JLabel();
        jLabelPollo5 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelSalida.setBackground(new java.awt.Color(73, 49, 44));
        jPanelSalida.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanelSalidaMouseDragged(evt);
            }
        });
        jPanelSalida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelSalidaMousePressed(evt);
            }
        });
        jPanelSalida.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/minimizar.png"))); // NOI18N
        btnMinimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMinimizarMouseClicked(evt);
            }
        });
        jPanelSalida.add(btnMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 14, -1, -1));

        btnSalir.setBackground(new java.awt.Color(73, 49, 44));
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salir.png"))); // NOI18N
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSalirMouseExited(evt);
            }
        });
        jPanelSalida.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 5, -1, -1));

        btnMaximizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/maximizar.png"))); // NOI18N
        btnMaximizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMaximizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMaximizarMouseClicked(evt);
            }
        });
        jPanelSalida.add(btnMaximizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 5, -1, -1));

        getContentPane().add(jPanelSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 40));

        jPanelHeader.setBackground(new java.awt.Color(193, 39, 45));
        jPanelHeader.setPreferredSize(new java.awt.Dimension(900, 180));
        jPanelHeader.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCarrito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carrito.png"))); // NOI18N
        btnCarrito.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCarrito.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCarritoMouseClicked(evt);
            }
        });
        jPanelHeader.add(btnCarrito, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 20, -1, -1));

        btnMenu.setBackground(new java.awt.Color(255, 211, 61));
        btnMenu.setFont(new java.awt.Font("Bebas Neue", 0, 48)); // NOI18N
        btnMenu.setForeground(new java.awt.Color(26, 26, 26));
        btnMenu.setText("MENú");
        btnMenu.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(193, 39, 45), 2, true));
        btnMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMenu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });
        jPanelHeader.add(btnMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 30, 120, -1));

        jlabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/donpollo-minilogo.png"))); // NOI18N
        jPanelHeader.add(jlabelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 5, -1, -1));

        getContentPane().add(jPanelHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 35, 910, 120));

        jScrollPane1.setBackground(new java.awt.Color(193, 39, 45));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 2));
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        background.setBackground(new java.awt.Color(248, 245, 240));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Bebas Neue", 0, 85)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(26, 26, 26));
        lblTitulo.setText("Postres");
     
        background.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, -1, -1));

        jPanelPechuga.setBackground(new java.awt.Color(193, 39, 45));
        jPanelPechuga.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelPechugaMouseClicked(evt);
            }
        });
        jPanelPechuga.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelPollo1.setBackground(new java.awt.Color(26, 26, 26));
        jLabelPollo1.setFont(new java.awt.Font("Lobster", 0, 28)); // NOI18N
        jLabelPollo1.setForeground(new java.awt.Color(248, 245, 240));
        jLabelPollo1.setText("Chocolate");
        jLabelPollo1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanelPechuga.add(jLabelPollo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 40, -1, 30));

        jh2_1.setBackground(new java.awt.Color(26, 26, 26));
        jh2_1.setFont(new java.awt.Font("Lobster", 0, 36)); // NOI18N
        jh2_1.setForeground(new java.awt.Color(248, 245, 240));
        jh2_1.setText("Pastel de");
        jh2_1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanelPechuga.add(jh2_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, -1));

        jLabel20.setText("jLabel2");
        jPanelPechuga.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 210, 100));

        background.add(jPanelPechuga, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 210, 180));

        jPanelAlita.setBackground(new java.awt.Color(193, 39, 45));
        jPanelAlita.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelAlitaMouseClicked(evt);
            }
        });
        jPanelAlita.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jh2_2.setBackground(new java.awt.Color(26, 26, 26));
        jh2_2.setFont(new java.awt.Font("Lobster", 0, 36)); // NOI18N
        jh2_2.setForeground(new java.awt.Color(248, 245, 240));
        jh2_2.setText("Helado");
        jh2_2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanelAlita.add(jh2_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, -1, 50));

        jLabelPollo2.setBackground(new java.awt.Color(26, 26, 26));
        jLabelPollo2.setFont(new java.awt.Font("Lobster", 0, 28)); // NOI18N
        jLabelPollo2.setForeground(new java.awt.Color(248, 245, 240));
        jLabelPollo2.setText("de Vainilla");
        jLabelPollo2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanelAlita.add(jLabelPollo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, 30));

        jLabel21.setText("jLabel2");
        jPanelAlita.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 210, 100));

        background.add(jPanelAlita, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, 210, 180));

        jPanelPierna.setBackground(new java.awt.Color(193, 39, 45));
        jPanelPierna.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelPiernaMouseClicked(evt);
            }
        });
        jPanelPierna.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jh2_3.setBackground(new java.awt.Color(26, 26, 26));
        jh2_3.setFont(new java.awt.Font("Lobster", 0, 36)); // NOI18N
        jh2_3.setForeground(new java.awt.Color(248, 245, 240));
        jh2_3.setText("Pay de");
        jh2_3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanelPierna.add(jh2_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, -1, 50));

        jLabelPollo3.setBackground(new java.awt.Color(26, 26, 26));
        jLabelPollo3.setFont(new java.awt.Font("Lobster", 0, 28)); // NOI18N
        jLabelPollo3.setForeground(new java.awt.Color(248, 245, 240));
        jLabelPollo3.setText("Limón");
        jLabelPollo3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanelPierna.add(jLabelPollo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, -1, 30));

        jLabel23.setText("jLabel2");
        jPanelPierna.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 210, 100));

        background.add(jPanelPierna, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 110, 210, 180));

        jPanelPicantePollo.setBackground(new java.awt.Color(193, 39, 45));
        jPanelPicantePollo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelPicantePolloMouseClicked(evt);
            }
        });
        jPanelPicantePollo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jh2_4.setBackground(new java.awt.Color(26, 26, 26));
        jh2_4.setFont(new java.awt.Font("Lobster", 0, 36)); // NOI18N
        jh2_4.setForeground(new java.awt.Color(248, 245, 240));
        jh2_4.setText("Helado");
        jh2_4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanelPicantePollo.add(jh2_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, -1, 50));

        jLabelPollo4.setBackground(new java.awt.Color(26, 26, 26));
        jLabelPollo4.setFont(new java.awt.Font("Lobster", 0, 28)); // NOI18N
        jLabelPollo4.setForeground(new java.awt.Color(248, 245, 240));
        jLabelPollo4.setText("Sundae");
        jLabelPollo4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanelPicantePollo.add(jLabelPollo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 90, 30));

        jLabel15.setText("jLabel2");
        jPanelPicantePollo.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 210, 100));

        background.add(jPanelPicantePollo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 210, 180));

        jPanelAlitas.setBackground(new java.awt.Color(193, 39, 45));
        jPanelAlitas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelAlitasMouseClicked(evt);
            }
        });
        jPanelAlitas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jh2_5.setBackground(new java.awt.Color(26, 26, 26));
        jh2_5.setFont(new java.awt.Font("Lobster", 0, 36)); // NOI18N
        jh2_5.setForeground(new java.awt.Color(248, 245, 240));
        jh2_5.setText("Flan de");
        jh2_5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanelAlitas.add(jh2_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, -1, 50));

        jLabelPollo5.setBackground(new java.awt.Color(26, 26, 26));
        jLabelPollo5.setFont(new java.awt.Font("Lobster", 0, 28)); // NOI18N
        jLabelPollo5.setForeground(new java.awt.Color(248, 245, 240));
        jLabelPollo5.setText("Caramelo");
        jLabelPollo5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanelAlitas.add(jLabelPollo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 120, -1));

        jLabel17.setText("jLabel2");
        jPanelAlitas.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 210, 100));

        background.add(jPanelAlitas, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 310, 210, 180));

        jLabel1.setForeground(new java.awt.Color(248, 245, 240));
        jLabel1.setText("jLabel1");
        background.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 1110, -1, 40));

        jScrollPane1.setViewportView(background);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 910, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizarMouseClicked
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_btnMinimizarMouseClicked

    private void btnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btnSalirMouseClicked

    private void btnSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseEntered

    }//GEN-LAST:event_btnSalirMouseEntered

    private void btnSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseExited

    }//GEN-LAST:event_btnSalirMouseExited

    private void btnMaximizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMaximizarMouseClicked
        this.setExtendedState(MAXIMIZED_BOTH);
    }//GEN-LAST:event_btnMaximizarMouseClicked

    private void jPanelSalidaMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelSalidaMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_jPanelSalidaMouseDragged

    private void jPanelSalidaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelSalidaMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jPanelSalidaMousePressed

    private void btnCarritoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCarritoMouseClicked
        CarritoComprasView carro = new CarritoComprasView();
       carro.setVisible(true);
       carro.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnCarritoMouseClicked

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        MenuOpciones menu = new MenuOpciones();
        menu.setVisible(true);
        menu.setLocationRelativeTo(null);
        setVisible(false);
    }//GEN-LAST:event_btnMenuActionPerformed

    private void jPanelPechugaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelPechugaMouseClicked
        opcUsuario = new PanelDescripcionDeCompra(16);
        opcUsuario.setVisible(true);
        opcUsuario.setLocationRelativeTo(this);
    }//GEN-LAST:event_jPanelPechugaMouseClicked

    private void jPanelAlitaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelAlitaMouseClicked
        opcUsuario = new PanelDescripcionDeCompra(17);
        opcUsuario.setVisible(true);
        opcUsuario.setLocationRelativeTo(this);
    }//GEN-LAST:event_jPanelAlitaMouseClicked

    private void jPanelPiernaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelPiernaMouseClicked
        opcUsuario = new PanelDescripcionDeCompra(18);
        opcUsuario.setVisible(true);
        opcUsuario.setLocationRelativeTo(this);
    }//GEN-LAST:event_jPanelPiernaMouseClicked

    private void jPanelPicantePolloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelPicantePolloMouseClicked
        opcUsuario = new PanelDescripcionDeCompra(19);
        opcUsuario.setVisible(true);
        opcUsuario.setLocationRelativeTo(this);
    }//GEN-LAST:event_jPanelPicantePolloMouseClicked

    private void jPanelAlitasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelAlitasMouseClicked
        opcUsuario = new PanelDescripcionDeCompra(20);
        opcUsuario.setVisible(true);
        opcUsuario.setLocationRelativeTo(this);
    }//GEN-LAST:event_jPanelAlitasMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PostresView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PostresView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PostresView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PostresView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PostresView1().setVisible(true);
            }
        });
    }
    
     private void setImageLabel(JLabel labelName, String root){
        ImageIcon image = new ImageIcon(root);
        Icon icon = new ImageIcon(image.getImage().getScaledInstance(210,100,Image.SCALE_SMOOTH));
        labelName.setIcon(icon);
        this.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JLabel btnCarrito;
    private javax.swing.JLabel btnMaximizar;
    private javax.swing.JButton btnMenu;
    private javax.swing.JLabel btnMinimizar;
    private javax.swing.JLabel btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabelPollo1;
    private javax.swing.JLabel jLabelPollo2;
    private javax.swing.JLabel jLabelPollo3;
    private javax.swing.JLabel jLabelPollo4;
    private javax.swing.JLabel jLabelPollo5;
    private javax.swing.JPanel jPanelAlita;
    private javax.swing.JPanel jPanelAlitas;
    private javax.swing.JPanel jPanelHeader;
    private javax.swing.JPanel jPanelPechuga;
    private javax.swing.JPanel jPanelPicantePollo;
    private javax.swing.JPanel jPanelPierna;
    private javax.swing.JPanel jPanelSalida;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jh2_1;
    private javax.swing.JLabel jh2_2;
    private javax.swing.JLabel jh2_3;
    private javax.swing.JLabel jh2_4;
    private javax.swing.JLabel jh2_5;
    private javax.swing.JLabel jlabelLogo;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
