/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.informatica.Interfaces;

import com.informatica.clases.DatosDelUsuario;
import java.awt.Color;
import com.informatica.clases.Usuarios_1;
/**
 *
 * @author Temporal
 */
public class RegistroView extends javax.swing.JFrame {

    /**
     * Creates new form RegistroView
     */
    int xMouse, yMouse;
    private CargarTipografias tipoFuente;
    public RegistroView() {
        setUndecorated(true);
        initComponents();
        
        tipoFuente = new CargarTipografias();
        
        btnRegistrarse.setFont(tipoFuente.fuente(tipoFuente.BebasNeue, 0, 40));
        jlabelPregunta.setFont(tipoFuente.fuente(tipoFuente.BebasNeue, 0, 25));
        
        btnIrLogin.setFont(tipoFuente.fuente(tipoFuente.Lobster, 0,25));
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelSalida = new javax.swing.JPanel();
        btnMinimizar = new javax.swing.JLabel();
        btnSalir = new javax.swing.JLabel();
        btnMaximizar = new javax.swing.JLabel();
        background = new javax.swing.JPanel();
        Header = new javax.swing.JPanel();
        alaIzq = new javax.swing.JLabel();
        alaDer = new javax.swing.JLabel();
        logoDonpollo = new javax.swing.JLabel();
        contenedorInfo = new javax.swing.JPanel();
        txtTelefono = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        btnRegistrarse = new javax.swing.JButton();
        txtPassword = new javax.swing.JPasswordField();
        jPanel3 = new javax.swing.JPanel();
        jlabelPregunta = new javax.swing.JLabel();
        btnIrLogin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelSalida.setBackground(new java.awt.Color(73, 49, 44));
        jPanelSalida.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanelSalidaMouseDragged(evt);
            }
        });
        jPanelSalida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelSalidaMousePressed(evt);
            }
        });
        jPanelSalida.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/minimizar.png"))); // NOI18N
        btnMinimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMinimizarMouseClicked(evt);
            }
        });
        jPanelSalida.add(btnMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 14, -1, -1));

        btnSalir.setBackground(new java.awt.Color(73, 49, 44));
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salir.png"))); // NOI18N
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSalirMouseExited(evt);
            }
        });
        jPanelSalida.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 5, -1, -1));

        btnMaximizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/maximizar.png"))); // NOI18N
        btnMaximizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMaximizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMaximizarMouseClicked(evt);
            }
        });
        jPanelSalida.add(btnMaximizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 5, -1, -1));

        getContentPane().add(jPanelSalida, java.awt.BorderLayout.PAGE_START);

        background.setBackground(new java.awt.Color(248, 245, 240));
        background.setLayout(new java.awt.BorderLayout());

        Header.setBackground(new java.awt.Color(248, 245, 240));

        alaIzq.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alaIzquierda.png"))); // NOI18N

        alaDer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alaDerecha.png"))); // NOI18N

        logoDonpollo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logoDonPollo.png"))); // NOI18N

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addComponent(alaIzq, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 175, Short.MAX_VALUE)
                .addComponent(logoDonpollo, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(173, 173, 173)
                .addComponent(alaDer))
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(alaIzq, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alaDer)
                    .addComponent(logoDonpollo, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        background.add(Header, java.awt.BorderLayout.PAGE_START);

        contenedorInfo.setBackground(new java.awt.Color(248, 245, 240));

        txtTelefono.setBackground(new java.awt.Color(248, 245, 240));
        txtTelefono.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        txtTelefono.setForeground(new java.awt.Color(102, 102, 102));
        txtTelefono.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTelefono.setText("Ingresa tu número de teléfono");
        txtTelefono.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(26, 26, 26), 3, true));
        txtTelefono.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtTelefonoMousePressed(evt);
            }
        });

        txtCorreo.setBackground(new java.awt.Color(248, 245, 240));
        txtCorreo.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        txtCorreo.setForeground(new java.awt.Color(102, 102, 102));
        txtCorreo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCorreo.setText("Ingresa tu correo");
        txtCorreo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(26, 26, 26), 3, true));
        txtCorreo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtCorreoMousePressed(evt);
            }
        });

        txtNombre.setBackground(new java.awt.Color(248, 245, 240));
        txtNombre.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(102, 102, 102));
        txtNombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNombre.setText("Ingresa tu nombre");
        txtNombre.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(26, 26, 26), 3, true));
        txtNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtNombreMousePressed(evt);
            }
        });

        btnRegistrarse.setBackground(new java.awt.Color(255, 211, 61));
        btnRegistrarse.setForeground(new java.awt.Color(26, 26, 26));
        btnRegistrarse.setText("Registrarse");
        btnRegistrarse.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(248, 245, 240), 3, true));
        btnRegistrarse.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarseActionPerformed(evt);
            }
        });

        txtPassword.setBackground(new java.awt.Color(248, 245, 240));
        txtPassword.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(102, 102, 102));
        txtPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPassword.setText("******");
        txtPassword.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(26, 26, 26), 3, true));
        txtPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtPasswordMousePressed(evt);
            }
        });

        javax.swing.GroupLayout contenedorInfoLayout = new javax.swing.GroupLayout(contenedorInfo);
        contenedorInfo.setLayout(contenedorInfoLayout);
        contenedorInfoLayout.setHorizontalGroup(
            contenedorInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedorInfoLayout.createSequentialGroup()
                .addContainerGap(204, Short.MAX_VALUE)
                .addGroup(contenedorInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contenedorInfoLayout.createSequentialGroup()
                        .addGroup(contenedorInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(202, 202, 202))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contenedorInfoLayout.createSequentialGroup()
                        .addComponent(btnRegistrarse, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(328, 328, 328))))
        );
        contenedorInfoLayout.setVerticalGroup(
            contenedorInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedorInfoLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(btnRegistrarse, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        background.add(contenedorInfo, java.awt.BorderLayout.CENTER);

        jPanel3.setBackground(new java.awt.Color(248, 245, 240));

        jlabelPregunta.setForeground(new java.awt.Color(26, 26, 26));
        jlabelPregunta.setText("¿Ya tienes una cuenta?");

        btnIrLogin.setBackground(new java.awt.Color(193, 39, 45));
        btnIrLogin.setForeground(new java.awt.Color(193, 39, 45));
        btnIrLogin.setText("Inicia Sesión");
        btnIrLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIrLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIrLoginMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 896, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 337, Short.MAX_VALUE)
                    .addComponent(jlabelPregunta)
                    .addGap(38, 38, 38)
                    .addComponent(btnIrLogin)
                    .addGap(0, 337, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(2, 2, 2)
                            .addComponent(jlabelPregunta))
                        .addComponent(btnIrLogin))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        background.add(jPanel3, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(background, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizarMouseClicked
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_btnMinimizarMouseClicked

    private void btnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btnSalirMouseClicked

    private void btnSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseEntered
        btnSalir.setBackground(new Color(193,39,45));
    }//GEN-LAST:event_btnSalirMouseEntered

    private void btnSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseExited
        btnSalir.setBackground(new Color(73,49,44));
    }//GEN-LAST:event_btnSalirMouseExited

    private void btnMaximizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMaximizarMouseClicked
        this.setExtendedState(MAXIMIZED_BOTH);
    }//GEN-LAST:event_btnMaximizarMouseClicked

    private void jPanelSalidaMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelSalidaMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_jPanelSalidaMouseDragged

    private void jPanelSalidaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelSalidaMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jPanelSalidaMousePressed

    private void btnIrLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIrLoginMouseClicked
        LoginView login = new LoginView();
        login.setVisible(true);
        login.setLocationRelativeTo(null);
        setVisible(false);
    }//GEN-LAST:event_btnIrLoginMouseClicked

    private void btnRegistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarseActionPerformed
        String nombre = txtNombre.getText();
        String email = txtCorreo.getText();
        int telefono = Integer.parseInt(txtTelefono.getText());
        String contra = new String(txtPassword.getPassword());
        
        Usuarios_1 user = new Usuarios_1(nombre,email,telefono,contra);
        DatosDelUsuario userAdmin = new DatosDelUsuario();
        if(userAdmin.agregarUsuario(user)){
            MenuMain menu = new MenuMain();
            menu.setVisible(true);
            menu.setLocationRelativeTo(null);
            setVisible(false);
        
        }
    }//GEN-LAST:event_btnRegistrarseActionPerformed

    private void txtNombreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreMousePressed
        if (txtNombre.getText().equals("Ingresa tu nombre")) {
        txtNombre.setText("");
        txtNombre.setForeground(new Color(26,26,26));
    }

    if (txtCorreo.getText().isEmpty()) {
        txtCorreo.setText("Ingresa tu correo");
        txtCorreo.setForeground(new Color(102,102,102));
    }
    if (txtTelefono.getText().isEmpty()) {
        txtTelefono.setText("Ingresa tu número de teléfono");
        txtTelefono.setForeground(new Color(102,102,102));
    }
    if (String.valueOf(txtPassword.getPassword()).isEmpty()) {
        txtPassword.setText("******");
        txtPassword.setForeground(new Color(102,102,102));
    }
    }//GEN-LAST:event_txtNombreMousePressed

    private void txtCorreoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCorreoMousePressed
        if (txtCorreo.getText().equals("Ingresa tu correo")) {
        txtCorreo.setText("");
        txtCorreo.setForeground(new Color(26,26,26));
    }

    if (txtNombre.getText().isEmpty()) {
        txtNombre.setText("Ingresa tu nombre");
        txtNombre.setForeground(new Color(102,102,102));
    }
    if (txtTelefono.getText().isEmpty()) {
        txtTelefono.setText("Ingresa tu número de teléfono");
        txtTelefono.setForeground(new Color(102,102,102));
    }
    if (String.valueOf(txtPassword.getPassword()).isEmpty()) {
        txtPassword.setText("******");
        txtPassword.setForeground(new Color(102,102,102));
    }
    }//GEN-LAST:event_txtCorreoMousePressed

    private void txtTelefonoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTelefonoMousePressed
        if (txtTelefono.getText().equals("Ingresa tu número de teléfono")) {
        txtTelefono.setText("");
        txtTelefono.setForeground(new Color(26,26,26));
    }

    if (txtNombre.getText().isEmpty()) {
        txtNombre.setText("Ingresa tu nombre");
        txtNombre.setForeground(new Color(102,102,102));
    }
    if (txtCorreo.getText().isEmpty()) {
        txtCorreo.setText("Ingresa tu correo");
        txtCorreo.setForeground(new Color(102,102,102));
    }
    if (String.valueOf(txtPassword.getPassword()).isEmpty()) {
        txtPassword.setText("******");
        txtPassword.setForeground(new Color(102,102,102));
    }
    }//GEN-LAST:event_txtTelefonoMousePressed

    private void txtPasswordMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPasswordMousePressed
        if (String.valueOf(txtPassword.getPassword()).equals("******")) {
        txtPassword.setText("");
        txtPassword.setForeground(new Color(26,26,26));
    }

    if (txtNombre.getText().isEmpty()) {
        txtNombre.setText("Ingresa tu nombre");
        txtNombre.setForeground(new Color(102,102,102));
    }
    if (txtCorreo.getText().isEmpty()) {
        txtCorreo.setText("Ingresa tu correo");
        txtCorreo.setForeground(new Color(102,102,102));
    }
    if (txtTelefono.getText().isEmpty()) {
        txtTelefono.setText("Ingresa tu número de teléfono");
        txtTelefono.setForeground(new Color(102,102,102));
    }
    }//GEN-LAST:event_txtPasswordMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Header;
    private javax.swing.JLabel alaDer;
    private javax.swing.JLabel alaIzq;
    private javax.swing.JPanel background;
    private javax.swing.JLabel btnIrLogin;
    private javax.swing.JLabel btnMaximizar;
    private javax.swing.JLabel btnMinimizar;
    private javax.swing.JButton btnRegistrarse;
    private javax.swing.JLabel btnSalir;
    private javax.swing.JPanel contenedorInfo;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelSalida;
    private javax.swing.JLabel jlabelPregunta;
    private javax.swing.JLabel logoDonpollo;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
