/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.informatica.ExtraInterfaces;

/**
 *
 * @author Temporal
 */
public class PanelDescripcionDeCompra extends javax.swing.JFrame {

    /**
     * Creates new form PanelDescripcion
     */
    private int xMouse,yMouse;
    public PanelDescripcionDeCompra() {
        setUndecorated(false);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BarraMovible = new javax.swing.JPanel();
        btnSalir = new javax.swing.JLabel();
        btnMinimizar = new javax.swing.JLabel();
        Background = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BarraMovible.setBackground(new java.awt.Color(73, 49, 44));
        BarraMovible.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                BarraMovibleMouseDragged(evt);
            }
        });
        BarraMovible.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BarraMovibleMousePressed(evt);
            }
        });
        BarraMovible.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSalir.setBackground(new java.awt.Color(73, 49, 44));
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salir.png"))); // NOI18N
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSalirMouseExited(evt);
            }
        });
        BarraMovible.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 4, -1, -1));

        btnMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/minimizar.png"))); // NOI18N
        btnMinimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMinimizarMouseClicked(evt);
            }
        });
        BarraMovible.add(btnMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 14, -1, -1));

        getContentPane().add(BarraMovible, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 40));

        Background.setBackground(new java.awt.Color(248, 245, 240));
        Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(26, 26, 26));
        jLabel1.setFont(new java.awt.Font("Lobster", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(26, 26, 26));
        jLabel1.setText("Precio:");
        Background.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, -1, -1));

        jLabel2.setBackground(new java.awt.Color(26, 26, 26));
        jLabel2.setFont(new java.awt.Font("Bebas Neue", 0, 28)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(26, 26, 26));
        jLabel2.setText("Q.00.00");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Background.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 80, 50));

        jLabel3.setBackground(new java.awt.Color(26, 26, 26));
        jLabel3.setFont(new java.awt.Font("Bebas Neue", 0, 29)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(26, 26, 26));
        jLabel3.setText("Paquete de Alitas de Pollo Fritas");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Background.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 50));

        jButton1.setBackground(new java.awt.Color(255, 211, 61));
        jButton1.setFont(new java.awt.Font("Bebas Neue", 0, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(26, 26, 26));
        jButton1.setText("Agregar al Carrito");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(248, 245, 240), 1, true));
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Background.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 170, 40));

        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 350, 160));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BarraMovibleMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarraMovibleMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_BarraMovibleMouseDragged

    private void BarraMovibleMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarraMovibleMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_BarraMovibleMousePressed

    private void btnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btnSalirMouseClicked

    private void btnSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseEntered

    }//GEN-LAST:event_btnSalirMouseEntered

    private void btnSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseExited

    }//GEN-LAST:event_btnSalirMouseExited

    private void btnMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizarMouseClicked
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_btnMinimizarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelDescripcionDeCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelDescripcionDeCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelDescripcionDeCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelDescripcionDeCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PanelDescripcionDeCompra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JPanel BarraMovible;
    private javax.swing.JLabel btnMinimizar;
    private javax.swing.JLabel btnSalir;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
