/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.informatica.VentanasSecundarias;

import com.informatica.DatosModel.CuponesDatos;
import com.informatica.DatosModel.DatosCarrito;
import com.informatica.DatosModel.DatosDeDireccion;
import com.informatica.DatosModel.ItemsEnCarrito;
import com.informatica.DatosModel.SesionUsuario;
import com.informatica.Interfaces.CargarTipografias;
import com.informatica.Interfaces.MenuMain;
import com.informatica.clases.Producto;
import javax.swing.JOptionPane;

/**
 *
 * @author Temporal
 */
public class DireccionView extends javax.swing.JFrame {

    /**
     * Creates new form DireccionView
     */
    private int yMouse,xMouse;
    private CargarTipografias tipoFuente;
    public DireccionView() {
        setUndecorated(false);
        initComponents();
        
        tipoFuente = new CargarTipografias();
        
        jLabelCalle.setFont(tipoFuente.fuente(tipoFuente.Lobster, 0,32));
        jLabelCiudad.setFont(tipoFuente.fuente(tipoFuente.Lobster, 0,32));
        jLabelDepa.setFont(tipoFuente.fuente(tipoFuente.Lobster, 0,32));
        
        jLabelagrega.setFont(tipoFuente.fuente(tipoFuente.BebasNeue,0,48));
        jLabelantesde.setFont(tipoFuente.fuente(tipoFuente.BebasNeue,0,48));
        btnFinPedido.setFont(tipoFuente.fuente(tipoFuente.BebasNeue,0,36));
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelSalida = new javax.swing.JPanel();
        btnMinimizar = new javax.swing.JLabel();
        btnSalir = new javax.swing.JLabel();
        btnMaximizar = new javax.swing.JLabel();
        jPanelHeader = new javax.swing.JPanel();
        jlabelLogo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabelagrega = new javax.swing.JLabel();
        jLabelantesde = new javax.swing.JLabel();
        jLabelCalle = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabelCiudad = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabelDepa = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        btnFinPedido = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelSalida.setBackground(new java.awt.Color(73, 49, 44));
        jPanelSalida.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanelSalidaMouseDragged(evt);
            }
        });
        jPanelSalida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelSalidaMousePressed(evt);
            }
        });
        jPanelSalida.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/minimizar.png"))); // NOI18N
        btnMinimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMinimizarMouseClicked(evt);
            }
        });
        jPanelSalida.add(btnMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 12, -1, -1));

        btnSalir.setBackground(new java.awt.Color(73, 49, 44));
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salir.png"))); // NOI18N
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSalirMouseExited(evt);
            }
        });
        jPanelSalida.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 4, -1, -1));

        btnMaximizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/maximizar.png"))); // NOI18N
        btnMaximizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMaximizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMaximizarMouseClicked(evt);
            }
        });
        jPanelSalida.add(btnMaximizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 4, -1, -1));

        getContentPane().add(jPanelSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 40));

        jPanelHeader.setBackground(new java.awt.Color(193, 39, 45));
        jPanelHeader.setPreferredSize(new java.awt.Dimension(900, 180));
        jPanelHeader.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/donpollo-minilogo.png"))); // NOI18N
        jPanelHeader.add(jlabelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 5, -1, -1));

        getContentPane().add(jPanelHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 35, 680, 120));

        jPanel1.setBackground(new java.awt.Color(248, 245, 240));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelagrega.setFont(new java.awt.Font("Bebas Neue", 0, 48)); // NOI18N
        jLabelagrega.setForeground(new java.awt.Color(26, 26, 26));
        jLabelagrega.setText("Agrega una dirreccion para tu pedido");
        jPanel1.add(jLabelagrega, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        jLabelantesde.setFont(new java.awt.Font("Bebas Neue", 0, 48)); // NOI18N
        jLabelantesde.setForeground(new java.awt.Color(26, 26, 26));
        jLabelantesde.setText("Antes de finalizar");
        jPanel1.add(jLabelantesde, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, -1, -1));

        jLabelCalle.setFont(new java.awt.Font("Lobster", 0, 32)); // NOI18N
        jLabelCalle.setForeground(new java.awt.Color(26, 26, 26));
        jLabelCalle.setText("Calle:");
        jPanel1.add(jLabelCalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, -1, -1));

        jTextField1.setBackground(new java.awt.Color(248, 245, 240));
        jTextField1.setFont(new java.awt.Font("Verdana", 1, 15)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(26, 26, 26));
        jTextField1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(26, 26, 26), 2, true));
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, 300, 30));

        jLabelCiudad.setFont(new java.awt.Font("Lobster", 0, 32)); // NOI18N
        jLabelCiudad.setForeground(new java.awt.Color(26, 26, 26));
        jLabelCiudad.setText("Ciudad:");
        jPanel1.add(jLabelCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, -1, -1));

        jTextField2.setBackground(new java.awt.Color(248, 245, 240));
        jTextField2.setFont(new java.awt.Font("Verdana", 1, 15)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(26, 26, 26));
        jTextField2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(26, 26, 26), 2, true));
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, 300, 30));

        jLabelDepa.setFont(new java.awt.Font("Lobster", 0, 32)); // NOI18N
        jLabelDepa.setForeground(new java.awt.Color(26, 26, 26));
        jLabelDepa.setText("Departamento:");
        jPanel1.add(jLabelDepa, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, -1, -1));

        jTextField3.setBackground(new java.awt.Color(248, 245, 240));
        jTextField3.setFont(new java.awt.Font("Verdana", 1, 15)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(26, 26, 26));
        jTextField3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(26, 26, 26), 2, true));
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 310, 300, 30));

        btnFinPedido.setBackground(new java.awt.Color(255, 211, 61));
        btnFinPedido.setFont(new java.awt.Font("Bebas Neue", 0, 36)); // NOI18N
        btnFinPedido.setForeground(new java.awt.Color(26, 26, 26));
        btnFinPedido.setText("Finalizar Pedido");
        btnFinPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinPedidoActionPerformed(evt);
            }
        });
        jPanel1.add(btnFinPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 400, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 680, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizarMouseClicked
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_btnMinimizarMouseClicked

    private void btnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btnSalirMouseClicked

    private void btnSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseEntered

    }//GEN-LAST:event_btnSalirMouseEntered

    private void btnSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseExited

    }//GEN-LAST:event_btnSalirMouseExited

    private void btnMaximizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMaximizarMouseClicked
        this.setExtendedState(MAXIMIZED_BOTH);
    }//GEN-LAST:event_btnMaximizarMouseClicked

    private void jPanelSalidaMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelSalidaMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_jPanelSalidaMouseDragged

    private void jPanelSalidaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelSalidaMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jPanelSalidaMousePressed

    private void btnFinPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinPedidoActionPerformed
        String calle = jTextField1.getText().trim();
        String ciudad = jTextField2.getText().trim();
        String departamento = jTextField3.getText().trim();
        
        if (!calle.isEmpty() || !ciudad.isEmpty() || !departamento.isEmpty()) {
            DatosDeDireccion datos = new DatosDeDireccion();
            DatosCarrito dc = new DatosCarrito();
            boolean guardado = datos.insertarDireccion(calle, ciudad, departamento);
            int id_user = SesionUsuario.getIdUsuarioActual();
            
            
            if (guardado) {
                GraxCompra agradecimiento = new GraxCompra();
                agradecimiento.setVisible(true);
                agradecimiento.setLocationRelativeTo(null);
                setVisible(false);
                ItemsEnCarrito.vaciarCarrito();
                dc.finalizarCompra(id_user);
                
                
            }else{
                JOptionPane.showMessageDialog(null, 
                "Error al guardar la dirección", 
                 "Error", 
                JOptionPane.ERROR_MESSAGE);
            }
        
        }else{
            JOptionPane.showMessageDialog(null, 
                "No puedes tener un campo vacio", 
                 "Campo Vacio", 
                JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btnFinPedidoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DireccionView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DireccionView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DireccionView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DireccionView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DireccionView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFinPedido;
    private javax.swing.JLabel btnMaximizar;
    private javax.swing.JLabel btnMinimizar;
    private javax.swing.JLabel btnSalir;
    private javax.swing.JLabel jLabelCalle;
    private javax.swing.JLabel jLabelCiudad;
    private javax.swing.JLabel jLabelDepa;
    private javax.swing.JLabel jLabelagrega;
    private javax.swing.JLabel jLabelantesde;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelHeader;
    private javax.swing.JPanel jPanelSalida;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel jlabelLogo;
    // End of variables declaration//GEN-END:variables
}
