/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.informatica.VentanasSecundarias;

import com.informatica.DatosModel.DatosDeProducto;
import com.informatica.Interfaces.CargarTipografias;
import com.informatica.clases.Producto;

/**
 *
 * @author Temporal
 */
public class PanelDescripcionDeCompra extends javax.swing.JFrame {

    /**
     * Creates new form PanelDescripcion
     */
    private int xMouse,yMouse;
    private CargarTipografias tipoFuente = new CargarTipografias();

    public PanelDescripcionDeCompra() {
        setUndecorated(true);
        initComponents();
        
        btnAddCarrito.setFont(tipoFuente.fuente(tipoFuente.BebasNeue, 0, 24));
        txtPrecio.setFont(tipoFuente.fuente(tipoFuente.BebasNeue,0,28));
        txtDescripcion.setFont(tipoFuente.fuente(tipoFuente.BebasNeue,0, 29));
        
        lblPrecio.setFont(tipoFuente.fuente(tipoFuente.Lobster,0,24));
        
    }
    
    
    
    public PanelDescripcionDeCompra(int opcionCliente) {
        this();
        /*
        Crea una clase de DatosDeProducto para que posteriormente mande la consulta SQL
        y luego crear una clase tipo Producto y acceder a los valores
        */
        DatosDeProducto productoSQL = new DatosDeProducto();
        Producto producto_normal = productoSQL.encontrarProducto(opcionCliente);
        
        if(producto_normal != null){
            if(producto_normal.getCantidad() >= 1){
                txtDescripcion.setText(String.valueOf(producto_normal.getDescripcion()));
                txtPrecio.setText(String.valueOf(producto_normal.getPrecio()));
            }else{
                txtPrecio.setText("Agotado");
            }
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelContenedor = new javax.swing.JPanel();
        BarraMovible = new javax.swing.JPanel();
        btnSalir = new javax.swing.JLabel();
        btnMinimizar = new javax.swing.JLabel();
        Background = new javax.swing.JPanel();
        lblPrecio = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JLabel();
        btnAddCarrito = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelContenedor.setBackground(new java.awt.Color(248, 245, 240));
        PanelContenedor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(73, 49, 44), 4));
        PanelContenedor.setVerifyInputWhenFocusTarget(false);
        PanelContenedor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BarraMovible.setBackground(new java.awt.Color(73, 49, 44));
        BarraMovible.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                BarraMovibleMouseDragged(evt);
            }
        });
        BarraMovible.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BarraMovibleMousePressed(evt);
            }
        });
        BarraMovible.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSalir.setBackground(new java.awt.Color(73, 49, 44));
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salir.png"))); // NOI18N
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSalirMouseExited(evt);
            }
        });
        BarraMovible.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 4, -1, -1));

        btnMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/minimizar.png"))); // NOI18N
        btnMinimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMinimizarMouseClicked(evt);
            }
        });
        BarraMovible.add(btnMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 14, -1, -1));

        PanelContenedor.add(BarraMovible, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 40));

        Background.setBackground(new java.awt.Color(248, 245, 240));
        Background.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(73, 49, 44), 3));
        Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPrecio.setBackground(new java.awt.Color(26, 26, 26));
        lblPrecio.setFont(new java.awt.Font("Lobster", 0, 24)); // NOI18N
        lblPrecio.setForeground(new java.awt.Color(26, 26, 26));
        lblPrecio.setText("Precio:");
        Background.add(lblPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, -1, -1));

        txtPrecio.setBackground(new java.awt.Color(26, 26, 26));
        txtPrecio.setFont(new java.awt.Font("Bebas Neue", 0, 28)); // NOI18N
        txtPrecio.setForeground(new java.awt.Color(26, 26, 26));
        txtPrecio.setText("Q.00.00");
        txtPrecio.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Background.add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 120, 50));

        txtDescripcion.setBackground(new java.awt.Color(26, 26, 26));
        txtDescripcion.setFont(new java.awt.Font("Bebas Neue", 0, 29)); // NOI18N
        txtDescripcion.setForeground(new java.awt.Color(26, 26, 26));
        txtDescripcion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtDescripcion.setText("Ensalada");
        txtDescripcion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Background.add(txtDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 10, 340, 50));

        btnAddCarrito.setBackground(new java.awt.Color(255, 211, 61));
        btnAddCarrito.setFont(new java.awt.Font("Bebas Neue", 0, 24)); // NOI18N
        btnAddCarrito.setForeground(new java.awt.Color(26, 26, 26));
        btnAddCarrito.setText("Agregar al Carrito");
        btnAddCarrito.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(248, 245, 240), 1, true));
        btnAddCarrito.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Background.add(btnAddCarrito, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 170, 40));

        PanelContenedor.add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 360, 160));

        getContentPane().add(PanelContenedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 359, 200));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BarraMovibleMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarraMovibleMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_BarraMovibleMouseDragged

    private void BarraMovibleMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarraMovibleMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_BarraMovibleMousePressed

    private void btnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseClicked
        dispose();
    }//GEN-LAST:event_btnSalirMouseClicked

    private void btnSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseEntered

    }//GEN-LAST:event_btnSalirMouseEntered

    private void btnSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseExited

    }//GEN-LAST:event_btnSalirMouseExited

    private void btnMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizarMouseClicked
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_btnMinimizarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelDescripcionDeCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelDescripcionDeCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelDescripcionDeCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelDescripcionDeCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PanelDescripcionDeCompra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JPanel BarraMovible;
    private javax.swing.JPanel PanelContenedor;
    private javax.swing.JButton btnAddCarrito;
    private javax.swing.JLabel btnMinimizar;
    private javax.swing.JLabel btnSalir;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel txtDescripcion;
    private javax.swing.JLabel txtPrecio;
    // End of variables declaration//GEN-END:variables
}
